#version 450

#include "dequant_head.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer A {block_q4_h data_a[];};
layout (binding = 1) writeonly buffer D {D_TYPE data_b[];};

void main() {
    const uint i = gl_WorkGroupID.x * 4 + gl_LocalInvocationID.x / 64;

    const uint tid = gl_LocalInvocationID.x % 64;
    const uint il  = tid/32;
    const uint ir  = tid%32;
    const uint ib = 32*i + ir;
    if (ib >= p.nel / 32) {
        return;
    }

    const uint b_idx = 1024*i + 32*ir + 8*il;

    // one fp32 reciprocal per block keeps the inner loop free of divisions
    const float d = 1.0f / float(data_a[ib].scale);
    const float z = float(data_a[ib].zero);

    const uint q_idx = 8*il;

    [[unroll]] for (uint l = 0; l < 8; ++l) {
        data_b[b_idx + l +  0] = D_TYPE((float(data_a[ib].qs[q_idx + l] & 0xF) - z) * d);
        data_b[b_idx + l + 16] = D_TYPE((float(data_a[ib].qs[q_idx + l] >>  4) - z) * d);
    }
}
