#version 450

#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer P {f16vec4 pState[];};
layout (binding = 1) readonly buffer V {float16_t vState[];};
layout (binding = 1) readonly buffer V_VEC2 {f16vec4 vStateVec[];};
layout (binding = 2) buffer MAX_FP32 {float max_f32[];};
layout (binding = 3) buffer SINK_FP32 {float sink_f32[];};
layout (binding = 4) buffer OUT_FP32 {float out_f32[];};
layout (binding = 5) buffer ACC_FP32 {float acc_f32[];};
layout (binding = 6) buffer SUM_FP32 {float sum_f32[];};
layout (binding = 7) buffer HIS_MAX_FP32 {float his_max_f32[];};

layout (push_constant) uniform parameter
{
  uint kvSeqLen;
  uint activationLength;
  uint qHead;
  uint kvHead;
  uint qkRatio;
  uint qkSubGroups;
  uint flag;
  uint kvStride;
  uint batchStrideQ;
  uint batchStrideK;
  uint batchStrideV;
  uint batchStrideM;
  uint batchStrideO;
  float softMaxScale;
} p;

layout (constant_id = 0) const uint GROUPSIZE = 32;
layout (constant_id = 1) const uint GQA_RATIO = 16;
layout (constant_id = 2) const uint HEAD_DIM = 128;
layout (constant_id = 3) const uint WARPSIZE = 16;
layout (constant_id = 4) const uint V_GROUPS_CONST = 2;
layout (constant_id = 5) const uint MATP_REDUCE_CONST = 64;
layout (constant_id = 6) const uint WARP_V_COUNT = 1;

#define MATP_REDUCE MATP_REDUCE_CONST
#define WARP_O_COUNT (WARP_V_COUNT * 4)

#define SUBGROUP_COUNT (GROUPSIZE / WARPSIZE)
#define MAX_COUNT ((GQA_RATIO + WARPSIZE - 1) / WARPSIZE)
#define SLM_SIZE_HIS_MAX (MAX_COUNT * WARPSIZE)
#define V_GROUPS V_GROUPS_CONST
#define P_GROUPS (SUBGROUP_COUNT / V_GROUPS)
#define O_COUNT ((GQA_RATIO * WARP_O_COUNT + WARPSIZE - 1) / WARPSIZE)
#define SLM_O_SIZE (O_COUNT * WARPSIZE * SUBGROUP_COUNT)
#define P_PER_ITER 32
#define V_HDIM_PER_ITER (P_PER_ITER / WARPSIZE)
#define MAT_P_ITER_COUNT (WARPSIZE / 4)
#define MACRO_LOOP 1
#define P_PER_WG 2048

shared float slm_pool_o[SLM_O_SIZE];
shared float slm_pool_softmax[SUBGROUP_COUNT * GQA_RATIO];
shared float slm_pool_historic_max[SLM_SIZE_HIS_MAX];

void main() {
  const uint lane = gl_SubgroupInvocationID;
  const uint h = gl_WorkGroupID.x;
  const uint v = gl_WorkGroupID.y;
  const uint totalPi = (p.kvSeqLen + P_PER_WG - 1) / P_PER_WG;
  const uint d = gl_WorkGroupID.z / totalPi;
  const uint piter = gl_WorkGroupID.z % totalPi;
  const uint localLinearId = gl_SubgroupID;
  const uint hhv = localLinearId % V_GROUPS;
  const uint vvv = localLinearId / V_GROUPS;
  const uint maxDim = p.kvSeqLen / MATP_REDUCE;
  const uint kvDim = p.kvStride;
  const uint oDim = p.qHead * HEAD_DIM;
  const uint maskDim = p.kvSeqLen;
  uint offsetBaseP = (d * p.qHead * p.kvSeqLen + v * GQA_RATIO * p.kvSeqLen + vvv * WARPSIZE + piter * P_PER_WG + lane * p.kvSeqLen) / 4;
  const uint offsetBaseV = (d * p.batchStrideV + v * HEAD_DIM + lane * kvDim + h * V_GROUPS * WARP_O_COUNT + (vvv * WARPSIZE + piter * P_PER_WG) * kvDim + hhv * WARP_O_COUNT) / 4;
  const uint offsetOut = d * p.batchStrideO + v * GQA_RATIO * HEAD_DIM + h * V_GROUPS * WARP_O_COUNT + localLinearId + lane * HEAD_DIM;
  const float fp32Min = uintBitsToFloat(0xFEFFFFFF);
  uint offsetV = offsetBaseV;
  uint offsetMax = (v * GQA_RATIO + lane);
  offsetMax = min(offsetMax, p.qHead - 1);
  offsetMax = offsetMax + d * p.qHead;
  offsetMax = offsetMax * maxDim + piter * P_PER_WG / MATP_REDUCE;

  f16vec4 matV[V_HDIM_PER_ITER][WARP_V_COUNT];
  f16vec4 matP[V_HDIM_PER_ITER][MAT_P_ITER_COUNT];
  float fp32O[WARP_O_COUNT];
  float historicMax = fp32Min;
  float softmaxSum = 0;
  float fp32SinkCoeff = fp32Min;

  [[unroll]] for (uint i = 0; i < WARP_O_COUNT; i++) {
    fp32O[i] = 0.0f;
  }

  const uint loopCount = P_PER_WG / P_GROUPS / P_PER_ITER;
  uint startP = piter * P_PER_WG + vvv * WARPSIZE;
  [[unroll]] for (uint loop = 0; loop < loopCount; loop++) {
    if (startP < p.kvSeqLen) {
      float currMax[V_HDIM_PER_ITER];
      float loopMax;
      float compensationO;
      float compensationP[V_HDIM_PER_ITER];

      [[unroll]] for (uint kk = 0; kk < V_HDIM_PER_ITER; kk++) {
        [[unroll]] for (uint nn = 0; nn < WARP_V_COUNT; nn++) {
          matV[kk][nn] = vStateVec[offsetV + nn];
        }

        [[unroll]] for (uint pn = 0; pn < MAT_P_ITER_COUNT; pn++) {
          matP[kk][pn] = pState[offsetBaseP + pn];
        }
        currMax[kk] = max_f32[offsetMax];
        offsetMax += 1;
        offsetV += WARPSIZE * P_GROUPS * kvDim / 4;
        offsetBaseP += WARPSIZE * P_GROUPS / 4;
      }

      loopMax = historicMax;
      [[unroll]] for (uint kk = 0; kk < V_HDIM_PER_ITER; kk++) {
        loopMax = max(currMax[kk], loopMax);
      }
      compensationO = exp(historicMax - loopMax);
      [[unroll]] for (uint kk = 0; kk < V_HDIM_PER_ITER; kk++) {
        compensationP[kk] = exp(currMax[kk] - loopMax);
      }
      softmaxSum = softmaxSum * compensationO;
      [[unroll]] for (uint oo = 0; oo < WARP_O_COUNT; oo++) {
        fp32O[oo] = fp32O[oo] * compensationO;
      }

      [[unroll]] for (uint kout = 0; kout < V_HDIM_PER_ITER; kout++) {
        [[unroll]] for (uint kin = 0; kin < MAT_P_ITER_COUNT; kin++) {
          float f32Temp[4] = float[4](float(matP[kout][kin].x) * compensationP[kout],
                                      float(matP[kout][kin].y) * compensationP[kout],
                                      float(matP[kout][kin].z) * compensationP[kout],
                                      float(matP[kout][kin].w) * compensationP[kout]);
          softmaxSum = softmaxSum + f32Temp[0];
          softmaxSum = softmaxSum + f32Temp[1];
          softmaxSum = softmaxSum + f32Temp[2];
          softmaxSum = softmaxSum + f32Temp[3];

          [[unroll]] for (uint vv = 0; vv < WARP_V_COUNT; vv++) {
            fp32O[4 * vv + 0] = fma(f32Temp[0], subgroupBroadcast(float(matV[kout][vv].x), 4 * kin + 0), fp32O[4 * vv + 0]);
            fp32O[4 * vv + 1] = fma(f32Temp[0], subgroupBroadcast(float(matV[kout][vv].y), 4 * kin + 0), fp32O[4 * vv + 1]);
            fp32O[4 * vv + 2] = fma(f32Temp[0], subgroupBroadcast(float(matV[kout][vv].z), 4 * kin + 0), fp32O[4 * vv + 2]);
            fp32O[4 * vv + 3] = fma(f32Temp[0], subgroupBroadcast(float(matV[kout][vv].w), 4 * kin + 0), fp32O[4 * vv + 3]);

            fp32O[4 * vv + 0] = fma(f32Temp[1], subgroupBroadcast(float(matV[kout][vv].x), 4 * kin + 1), fp32O[4 * vv + 0]);
            fp32O[4 * vv + 1] = fma(f32Temp[1], subgroupBroadcast(float(matV[kout][vv].y), 4 * kin + 1), fp32O[4 * vv + 1]);
            fp32O[4 * vv + 2] = fma(f32Temp[1], subgroupBroadcast(float(matV[kout][vv].z), 4 * kin + 1), fp32O[4 * vv + 2]);
            fp32O[4 * vv + 3] = fma(f32Temp[1], subgroupBroadcast(float(matV[kout][vv].w), 4 * kin + 1), fp32O[4 * vv + 3]);

            fp32O[4 * vv + 0] = fma(f32Temp[2], subgroupBroadcast(float(matV[kout][vv].x), 4 * kin + 2), fp32O[4 * vv + 0]);
            fp32O[4 * vv + 1] = fma(f32Temp[2], subgroupBroadcast(float(matV[kout][vv].y), 4 * kin + 2), fp32O[4 * vv + 1]);
            fp32O[4 * vv + 2] = fma(f32Temp[2], subgroupBroadcast(float(matV[kout][vv].z), 4 * kin + 2), fp32O[4 * vv + 2]);
            fp32O[4 * vv + 3] = fma(f32Temp[2], subgroupBroadcast(float(matV[kout][vv].w), 4 * kin + 2), fp32O[4 * vv + 3]);

            fp32O[4 * vv + 0] = fma(f32Temp[3], subgroupBroadcast(float(matV[kout][vv].x), 4 * kin + 3), fp32O[4 * vv + 0]);
            fp32O[4 * vv + 1] = fma(f32Temp[3], subgroupBroadcast(float(matV[kout][vv].y), 4 * kin + 3), fp32O[4 * vv + 1]);
            fp32O[4 * vv + 2] = fma(f32Temp[3], subgroupBroadcast(float(matV[kout][vv].z), 4 * kin + 3), fp32O[4 * vv + 2]);
            fp32O[4 * vv + 3] = fma(f32Temp[3], subgroupBroadcast(float(matV[kout][vv].w), 4 * kin + 3), fp32O[4 * vv + 3]);
          }
        }
      }

      historicMax = loopMax;
      startP += P_GROUPS * P_PER_ITER;
    }
  }

  [[unroll]] for (uint oo = 0; oo < WARP_O_COUNT; oo++) {
    slm_pool_o[hhv * WARP_O_COUNT * GQA_RATIO * P_GROUPS + oo * GQA_RATIO * P_GROUPS + lane * P_GROUPS + vvv] = fp32O[oo];
  }

  if (hhv == 0) {
    slm_pool_softmax[lane * P_GROUPS + vvv] = softmaxSum;
  }

  barrier();
  const uint accOffset = offsetOut * totalPi + piter;
  float softmaxAcc;

  if (localLinearId < V_GROUPS * WARP_O_COUNT) {
    float fp32SlmTempO[P_GROUPS];
    float fp32SlmTempSoftmax[P_GROUPS];
    float softmaxMul;

    const uint slmOffsetLoad = localLinearId * GQA_RATIO * P_GROUPS + lane * P_GROUPS;
    [[unroll]] for (uint split = 0; split < P_GROUPS; split++) {
      fp32SlmTempO[split] = slm_pool_o[slmOffsetLoad + split];
    }

    [[unroll]] for (uint split = 0; split < P_GROUPS; split++) {
      fp32SlmTempSoftmax[split] = slm_pool_softmax[lane * P_GROUPS + split];
    }

    softmaxAcc = fp32SlmTempSoftmax[0] + fp32SlmTempSoftmax[1];
    [[unroll]] for (uint oc = 2; oc < P_GROUPS; oc++) {
      softmaxAcc = softmaxAcc + fp32SlmTempSoftmax[oc];
    }

    fp32O[0] = fp32SlmTempO[0] + fp32SlmTempO[1];
    [[unroll]] for (uint split = 2; split < P_GROUPS; split++) {
      fp32O[0] = fp32O[0] + fp32SlmTempO[split];
    }

    if (0x1 == (p.flag & 0x1)) {
      float fp32SinkCoeff;
      float sinkCompensation;
      float softmaxSumTemp;
      fp32SinkCoeff = sink_f32[v * GQA_RATIO + lane];

      fp32SinkCoeff = historicMax - fp32SinkCoeff;
      sinkCompensation = exp(sinkCompensation);
      softmaxSumTemp = softmaxAcc * sinkCompensation;
      softmaxMul = softmaxAcc + 1.0f / sinkCompensation;
      softmaxMul = 1.0f / softmaxMul;
      sinkCompensation = sinkCompensation / (1.0f + softmaxSumTemp);
      softmaxMul = historicMax < fp32SinkCoeff ? sinkCompensation : softmaxMul;
    } else {
      softmaxMul = 1.0f / softmaxAcc;
    }

    if (totalPi == 1) {
      fp32O[0] = fp32O[0] * softmaxMul;
      out_f32[offsetOut] = fp32O[0];
    } else {
      acc_f32[accOffset] = fp32O[0];
    }
  }

  if (totalPi > 1) {
    if ((localLinearId == 0) && (h == 0)) {
      const uint sumMaxOutOffset = d * p.qHead  * totalPi + (v * GQA_RATIO + lane) * totalPi + piter;
      sum_f32[sumMaxOutOffset] = softmaxAcc;
      his_max_f32[sumMaxOutOffset] = historicMax;
    }
  }
}
