#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require

#include "mul_mat_vec_base.glsl"

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

FLOAT_TYPE temp[NUM_COLS][NUM_ROWS];

void calc_block(const uint a_offset, const uint b_offset, const uint itid, const uint i, const uint num_blocks_per_row, const uint first_row, const uint num_rows) {
    const uint y_idx = i * QUANT_K + 4 * itid;

    float d[NUM_ROWS];
    uint qsw[NUM_ROWS];
    uint qhw[NUM_ROWS];
    uint ibi = a_offset + first_row * num_blocks_per_row + i;
    [[unroll]] for (uint n = 0; n < num_rows; ++n) {
        d[n]   = float(data_a[ibi].d);
        qhw[n] = pack32(u16vec2(data_a_packed16[ibi].qh[0], data_a_packed16[ibi].qh[1]));
        qsw[n] = pack32(u16vec2(data_a_packed16[ibi].qs[2 * itid],
                                data_a_packed16[ibi].qs[2 * itid + 1]));
        ibi += num_blocks_per_row;
    }

    [[unroll]] for (uint g = 0; g < 4; ++g) {
        vec4 v[NUM_ROWS];
        [[unroll]] for (uint n = 0; n < num_rows; ++n) {
            const uint qh_g = (qhw[n] >> (8 * g)) >> (4 * itid);
            const u8vec4 q = unpack8(((qsw[n] >> (2 * g)) & 0x03030303) | iq3nl_hbits4(qh_g));
            v[n] = d[n] * vec4(kvalues_iq3nl[q.x], kvalues_iq3nl[q.y], kvalues_iq3nl[q.z], kvalues_iq3nl[q.w]);
        }

        [[unroll]] for (uint j = 0; j < NUM_COLS; ++j) {
            const vec4 b = vec4(data_b_v4[(j * p.batch_stride_b + b_offset + y_idx) / 4 + 2 * g]);
            [[unroll]] for (uint n = 0; n < num_rows; ++n) {
                temp[j][n] += FLOAT_TYPE(dot(b, v[n]));
            }
        }
    }
}

void compute_outputs(const uint32_t first_row, const uint32_t num_rows) {
    uint a_offset, b_offset, d_offset;
    get_offsets(a_offset, b_offset, d_offset);

    const uint num_blocks_per_row = p.ncols / QUANT_K;

    // 2 threads are used to process each block
    const uint blocks_per_wg = gl_WorkGroupSize.x / 2;
    const uint tid = gl_LocalInvocationID.x;
    const uint itid = tid % 2;
    const uint ix = tid / 2;

    [[unroll]] for (uint j = 0; j < NUM_COLS; ++j) {
        [[unroll]] for (uint i = 0; i < NUM_ROWS; ++i) {
            temp[j][i] = FLOAT_TYPE(0);
        }
    }

    [[unroll]] for (uint i = ix; i < num_blocks_per_row; i += blocks_per_wg)
        calc_block(a_offset, b_offset, itid, i, num_blocks_per_row, first_row, num_rows);

    reduce_result(temp, d_offset, first_row, num_rows, tid);
}

void main() {
    const uint first_row = NUM_ROWS * (gl_WorkGroupID.x + gl_NumWorkGroups.x * gl_WorkGroupID.z);

    init_iq_shmem(gl_WorkGroupSize);

    // do NUM_ROWS at a time, unless there aren't enough remaining rows
    if (first_row + NUM_ROWS <= p.stride_d) {
        compute_outputs(first_row, NUM_ROWS);
    } else {
        if (first_row >= p.stride_d) {
            return;
        }
        compute_outputs(first_row, p.stride_d - first_row);
    }
}
