// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-f16.cuh"

#ifdef GGML_CUDA_FA_ALL_QUANTS
DECL_FATTN_MMA_F16_CASE(128, 128, 16, 1, GGML_TYPE_Q8_0, GGML_TYPE_Q4_0);
DECL_FATTN_MMA_F16_CASE(256, 256, 16, 1, GGML_TYPE_Q8_0, GGML_TYPE_Q4_0);
#endif // GGML_CUDA_FA_ALL_QUANTS
