// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-mma-bf16.cuh"

DECL_FATTN_MMA_BF16_CASE(320, 256, 2, 32);
DECL_FATTN_MMA_BF16_CASE(576, 512, 2, 32);
