#!/usr/bin/env python3
#
# gen_flrq_fixture.py
#
# Generates a deterministic fixture for the C++ FLRQ parity test
# (tools/quantize/tessera/test_flrq.cpp). Builds a small weight matrix with
# injected outliers, runs Python's flrq_sketch + flrq_bcl (the deterministic
# numerical core of tools/tessera/per_tensor_calibrate.py), and writes the
# inputs (W, U_basis) plus the Python-computed outputs (U, V, residual,
# residual_q, scale, clip, mse) to fixtures/flrq_fixture.json.
#
# The C++ test loads W and U_basis, runs ts_flrq_bcl on the SAME basis, and
# asserts parity on the BLC outputs. Because the basis is loaded from the
# fixture (rather than regenerated by a different RNG), the BLC step -- the
# outlier-aware low-rank fit + clip residual numerical core -- is pinned
# bit-for-bit (up to per-column sign of the basis, which leaves U@V, residual,
# and residual_q invariant).
#
# Regenerate:
#   python3 tools/quantize/tessera/fixtures/gen_flrq_fixture.py
#
# All RNG is seeded so the fixture is byte-stable.

from __future__ import annotations

import importlib.util
import json
import math
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent.parent.parent  # repo root
PTC = REPO / "tools" / "tessera" / "per_tensor_calibrate.py"


def load_per_tensor_calibrate():
    spec = importlib.util.spec_from_file_location("per_tensor_calibrate", str(PTC))
    m = importlib.util.module_from_spec(spec)
    sys.modules["per_tensor_calibrate"] = m
    spec.loader.exec_module(m)
    return m


def main() -> int:
    ptc = load_per_tensor_calibrate()
    flrq_sketch = ptc.flrq_sketch
    flrq_bcl = ptc.flrq_bcl

    # Small but non-trivial weight: 16 x 32, Kaiming-ish scale, with a few
    # injected outlier rows + a low-rank "outlier subspace" so the R1-Sketch
    # basis is non-degenerate and the residual fold actually engages.
    rng = np.random.default_rng(0xF1A6)
    K, N = 16, 32
    in_dim = N
    W = rng.normal(0.0, 1.0 / math.sqrt(in_dim), size=(K, N)).astype(np.float32)
    # planted low-rank outlier subspace (rank 3)
    U_out = rng.normal(0.0, 0.5, size=(K, 3)).astype(np.float32)
    V_out = rng.normal(0.0, 0.5 / math.sqrt(3), size=(3, N)).astype(np.float32)
    W = (W + U_out @ V_out).astype(np.float32)
    # a few large-magnitude rows (channel outliers) -> exercised residual clip
    for idx in (2, 9):
        W[idx] *= 12.0

    # FLRQ config. n_projections and r chosen so total_width = min(N, n_proj*r)
    # is full-rank in N, giving a clean SVD comparison.
    n_projections = 8
    r = 4
    blc_iters = 4
    qbits = 4
    seed = 0

    # 1. R1-Sketch: build the basis the C++ test will load. We pin the basis
    #    here so the BLC parity does not depend on the C++ sketch RNG.
    Y, U_basis, sigma = flrq_sketch(
        W, n_projections=n_projections, seed=seed, target_rank=r
    )

    # 2. BLC: the deterministic numerical core.
    U, V, scale, clip, residual, residual_q = flrq_bcl(
        W, U_basis, n_iters=blc_iters, qbits=qbits
    )
    recon = U @ V + residual_q
    diff = W - recon
    reconstruction_mse = float(np.sum(diff * diff) / (K * N))
    w_fro2 = float(np.sum(W * W)) + 1e-12
    reconstruction_rel_mse = float(np.sum(diff * diff) / w_fro2)

    # Low-rank product (sign-invariant ground truth for the test).
    low_rank = U @ V

    fixture = {
        "schema": "llama.tessera.flrq-fixture.v1",
        "config": {
            "K": int(K),
            "N": int(N),
            "n_projections": int(n_projections),
            "rank": int(r),
            "blc_iters": int(blc_iters),
            "qbits": int(qbits),
            "seed": int(seed),
        },
        "input": {
            "weight": W.astype(np.float32).tolist(),
            "U_basis": U_basis.astype(np.float32).tolist(),
        },
        "expected": {
            "U": U.astype(np.float32).tolist(),
            "V": V.astype(np.float32).tolist(),
            "low_rank": low_rank.astype(np.float32).tolist(),
            "residual": residual.astype(np.float32).tolist(),
            "residual_q": residual_q.astype(np.float32).tolist(),
            "scale": float(scale),
            "clip": float(clip),
            "reconstruction_mse": float(reconstruction_mse),
            "reconstruction_rel_mse": float(reconstruction_rel_mse),
        },
    }

    out_path = HERE / "flrq_fixture.json"
    out_path.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out_path}")
    print(
        f"  W=({K}x{N}) r={r} blc_iters={blc_iters} qbits={qbits}  "
        f"scale={scale:.4e} clip={clip:.4f}  "
        f"recon_mse={reconstruction_mse:.4e} rel={reconstruction_rel_mse:.4e}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
