#!/usr/bin/env python3
#
# gen_dartquant_fixture.py
#
# Generates a deterministic fixture for the C++ DartQuant parity test
# (tools/quantize/tessera/test_dartquant.cpp). Builds a small weight matrix
# (16x32) plus a calibration activation block and per-input-channel scale
# (X_hat = sqrt(E[x^2])), then runs Python's dartquant_qr_orth and writes
# both the inputs and the Python-computed outputs (rotation matrix R, loss
# history, whip / quant-mse / output-mse trajectories) to
# fixtures/dartquant_fixture.json.
#
# The C++ test loads this JSON, runs the C++ port on the same inputs, and
# asserts numerical parity. Regenerate by running this script once:
#
#   python3 tools/quantize/tessera/fixtures/gen_dartquant_fixture.py
#
# All RNG is seeded so the fixture is byte-stable. We initialise R = I
# (seed = 0) on both sides so the random-orthogonal initialisation (which
# differs between numpy and the C++ xorshift PRNG) does not perturb the
# parity comparison.
#

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent.parent.parent  # repo root
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from tools.tessera.per_tensor_calibrate import (  # noqa: E402
    dartquant_apply_rotation,
    dartquant_qr_orth,
    dartquant_whip_loss,
    _relative_quant_mse,
    _output_mse_and_grad,
    _whip_grad_impl,
)


def _synthetic(out_dim: int, in_dim: int, num_samples: int, seed: int):
    """Mirror of dartquant_demo._synthetic: skewed input-channel recipe."""
    rng = np.random.default_rng(seed)
    W = rng.normal(
        loc=0.0, scale=1.0 / math.sqrt(in_dim), size=(out_dim, in_dim)
    ).astype(np.float32)
    col_scale = np.ones(in_dim, dtype=np.float32)
    strong = rng.choice(in_dim, size=max(1, in_dim // 5), replace=False)
    col_scale[strong] = 5.0
    W = (W * col_scale[None, :]).astype(np.float32)
    x_scale = col_scale.astype(np.float32)
    x = rng.normal(loc=0.0, scale=1.0, size=(num_samples, in_dim)).astype(np.float32)
    x = (x * x_scale[None, :]).astype(np.float32)
    X_hat = (x_scale.astype(np.float32) ** 2).astype(np.float32)
    return W, x, X_hat, x_scale


def arr(a):
    return np.asarray(a).astype(np.float32).flatten().tolist()


def main() -> int:
    out_dim = 16
    in_dim = 32
    num_samples = 8
    n_iters = 30
    lr = 1.0e-2
    whip_weight = 0.1
    seed = 0  # identity init; keeps numpy vs C++ random paths out of parity.

    W, X, X_hat, x_scale = _synthetic(out_dim, in_dim, num_samples, seed)

    result = dartquant_qr_orth(
        W,
        X=X,
        X_hat=X_hat,
        n_iters=n_iters,
        lr=lr,
        whip_weight=whip_weight,
        seed=seed,
        verbose=False,
    )

    # Recompute the per-iteration trajectory on the *final* schedule path so
    # the C++ side can assert loss-trajectory parity step-by-step. We replay
    # the QR-Orth loop here (mirrors dartquant_qr_orth's body) and stash the
    # per-iter (qmse, whip, omse, combined) for the first few and last step.
    from tools.tessera._dartquant_linalg import qr_orth_step

    Wf = np.ascontiguousarray(W.astype(np.float32))
    R = np.eye(in_dim, dtype=np.float32)
    init_qmse = _relative_quant_mse(dartquant_apply_rotation(Wf, R))
    init_whip = dartquant_whip_loss(dartquant_apply_rotation(Wf, R), X_hat=X_hat)
    init_omse, _ = _output_mse_and_grad(Wf, R, X)
    trajectory = [{
        "iter": -1,
        "quant_mse": float(init_qmse),
        "whip": float(init_whip),
        "output_mse": float(init_omse),
        "combined": float(init_qmse + whip_weight * init_whip),
    }]
    for it in range(n_iters):
        _, q_grad = _output_mse_and_grad(Wf, R, X)
        w_grad = _whip_grad_impl(Wf, R, X_hat)
        total_grad = q_grad + float(whip_weight) * w_grad
        R = qr_orth_step(R.astype(np.float64), total_grad.astype(np.float64), lr).astype(np.float32)
        Wp = dartquant_apply_rotation(Wf, R)
        q = _relative_quant_mse(Wp)
        w = dartquant_whip_loss(Wp, X_hat=X_hat)
        o, _ = _output_mse_and_grad(Wf, R, X)
        trajectory.append({
            "iter": int(it),
            "quant_mse": float(q),
            "whip": float(w),
            "output_mse": float(o),
            "combined": float(q + whip_weight * w),
        })

    # Final-R verification metrics (recomputed off result.rotation so the C++
    # side has a single source of truth for the parity targets).
    Wp_final = dartquant_apply_rotation(Wf, result.rotation)
    final_qmse = _relative_quant_mse(Wp_final)
    final_whip = dartquant_whip_loss(Wp_final, X_hat=X_hat)
    final_omse, _ = _output_mse_and_grad(Wf, result.rotation, X)

    fixture = {
        "version": 1,
        "comment": "Generated by gen_dartquant_fixture.py; do not edit by hand.",
        "tolerance": {
            # The QR-Orth path uses float32 matmuls in C++ vs float32-then-
            # float64 QR in Python, so the iterate diverges ~1e-3 per step.
            # We therefore check loss / output parity tightly and the rotation
            # loosely (with sign / -R acceptance documented in the test).
            "loss_combined_atol": 5.0e-3,
            "whip_atol": 5.0e-3,
            "quant_mse_atol": 5.0e-3,
            "output_mse_atol": 5.0e-3,
            "rotation_max_abs_atol": 5.0e-2,
            "rotation_orthogonality_atol": 1.0e-3,
        },
        "params": {
            "out_dim": int(out_dim),
            "in_dim": int(in_dim),
            "block_size": int(in_dim),
            "num_samples": int(num_samples),
            "n_iters": int(n_iters),
            "lr": float(lr),
            "whip_weight": float(whip_weight),
            "seed": int(seed),
        },
        "inputs": {
            "weight": arr(W),
            "X": arr(X),
            "X_hat": arr(X_hat),
            "x_scale": arr(x_scale),
        },
        "expected": {
            "rotation": arr(result.rotation),
            "history": [float(h) for h in result.history],
            "initial_whip": float(result.initial_whip),
            "final_whip": float(result.final_whip),
            "initial_quant_mse": float(result.initial_quant_mse),
            "final_quant_mse": float(result.final_quant_mse),
            "initial_output_mse": float(result.initial_output_mse),
            "final_output_mse": float(result.final_output_mse),
            "iterations": int(result.iterations),
            # Recomputed off the final rotation; the C++ test re-derives these
            # from the same R so both sides agree on the deployment metric.
            "final_quant_mse_redrive": float(final_qmse),
            "final_whip_redrive": float(final_whip),
            "final_output_mse_redrive": float(final_omse),
        },
        "trajectory": trajectory,
    }

    out_path = HERE / "dartquant_fixture.json"
    with open(out_path, "w") as f:
        json.dump(fixture, f, indent=2, sort_keys=True)
    print(f"wrote {out_path} ({out_path.stat().st_size} bytes)")
    print(f"  W shape: ({out_dim}, {in_dim})  X shape: ({num_samples}, {in_dim})")
    print(f"  initial: whip={result.initial_whip:.4e} qmse={result.initial_quant_mse:.4e} omse={result.initial_output_mse:.4e}")
    print(f"  final:   whip={result.final_whip:.4e} qmse={result.final_quant_mse:.4e} omse={result.final_output_mse:.4e}")
    print(f"  R orthogonality err: {np.max(np.abs(result.rotation.T @ result.rotation - np.eye(in_dim))):.2e}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
