#!/usr/bin/env python3
#
# gen_septq_fixture.py
#
# Generates a deterministic fixture for the C++ SEPTQ parity test
# (tools/quantize/tessera/test_septq.cpp). Builds a small random weight
# matrix + calibration activations, runs Python's quantize_2d_septq and
# the helpers _septq_banded_cholesky / _septq_gptq_M / _septq_build_hessian,
# and writes both the inputs and the Python-computed outputs to
# fixtures/septq_fixture.json.
#
# The C++ test loads this JSON, runs the C++ port on the same inputs, and
# asserts numerical parity. Regenerate by running this script once:
#
#   python3 tools/quantize/tessera/fixtures/gen_septq_fixture.py
#
# All RNG is seeded so the fixture is byte-stable.
#

from __future__ import annotations

import importlib.util
import json
import math
import os
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent.parent.parent  # repo root
QV3_PY = REPO / "tools" / "tile640" / "quantize_v3.py"


def load_quantize_v3():
    spec = importlib.util.spec_from_file_location("quantize_v3", str(QV3_PY))
    m = importlib.util.module_from_spec(spec)
    sys.modules["quantize_v3"] = m
    spec.loader.exec_module(m)
    return m


def arr(a):
    return np.asarray(a).astype(np.float32).flatten().tolist()


def iarr(a):
    return np.asarray(a).flatten().tolist()


def main() -> int:
    qv3 = load_quantize_v3()

    rng = np.random.default_rng(0x5E7)
    out_dim = 16
    in_dim = 32
    n_tokens = 24
    bandwidth = 8
    septq_ratio = 0.6

    # Heavy-tailed weights so the importance ranking is non-trivial and the
    # outlier (full-precision) path actually engages.
    weight = (rng.standard_normal((out_dim, in_dim)) * 0.5).astype(np.float32)
    weight[:, 3] *= 4.0
    weight[2, 7] = 3.0
    activations = rng.standard_normal((n_tokens, in_dim)).astype(np.float32)

    # --- Intermediate helpers (parity-checked separately) ---
    H = qv3._septq_build_hessian(in_dim, None, activations)
    L = qv3._septq_banded_cholesky(H, bandwidth)
    M = qv3._septq_gptq_M(L, bandwidth)

    # --- Full quantizer ---
    res = qv3.quantize_2d_septq(
        weight, out_dim, in_dim,
        septq_ratio=septq_ratio,
        calibration_activations=activations,
        septq_hessian_mode="banded",
        septq_hessian_bandwidth=bandwidth,
    )

    ternary = np.asarray(res["_ternary"]).astype(np.int8)
    mask_2d = np.asarray(res["_mask_2d"]).astype(bool)

    # Final-quantized reconstruction: ternary where masked-quantized, else
    # the compensated outlier value. The C++ test compares the discrete
    # ternary/mask arrays (exact) and the outlier_vals float bucket.
    outlier_cols = np.asarray(res["outlier_cols"]).astype(np.int64)
    outlier_vals_f16 = np.asarray(res["outlier_vals"]).astype(np.float16)

    # Packed ternary tiles + per-page/per-lane scales (canonical Tessera
    # on-disk components). The Python "packed" is uint32 base-3 words;
    # page_scales are f16 bits; lane_scales are int8 in [1, 127].
    packed_u32 = np.asarray(res["packed"]).astype(np.uint32)
    page_scales_f16 = np.asarray(res["page_scales"]).astype(np.float16)
    lane_scales_i8 = np.asarray(res["lane_scales"]).astype(np.int8)

    fixture = {
        "version": 1,
        "comment": "Generated by gen_septq_fixture.py; do not edit by hand.",
        "tolerance": {
            # Hessian H: numpy builds X^T X in float32 BLAS; the C++ port
            # accumulates in float64 and casts to float32. The 1-ULP gap is
            # unavoidable, ~2.4e-7 on this fixture.
            "H_atol": 1e-6,
            # L: banded Cholesky is a scalar f32 loop on both sides, so it
            # matches to f32 rounding given the same H. The residual is the
            # H divergence propagated through sqrt/dot, ~1e-6.
            "L_atol": 1e-6,
            # M: forward-substitution amplifies the L delta; ~1e-5.
            "M_atol": 1e-5,
            # ternary / mask are discrete -> exact match expected.
            "ternary_exact": True,
            "mask_exact": True,
            # packed tiles / page_scales / lane_scales are deterministic
            # functions of the ternary + original weights -> exact match.
            "packed_exact": True,
            "page_scales_exact": True,
            "lane_scales_exact": True,
            # outlier_vals are stored as float16. W_comp agrees with Python
            # to ~1e-5, but a few values sit on f16 rounding boundaries at
            # tiny magnitudes, so a handful may differ by <=4 f16 ULPs.
            "outlier_vals_max_ulp": 4,
        },
        "config": {
            "out_dim": int(out_dim),
            "in_dim": int(in_dim),
            "n_tokens": int(n_tokens),
            "bandwidth": int(bandwidth),
            "septq_ratio": float(septq_ratio),
            "ternary_threshold": 1.0,
            "ridge_fraction": 1e-4,
            "importance_weight": "quant_error_h",
            "importance_lambda": 0.0,
            "hessian_mode": "banded",
        },
        "inputs": {
            "weight": arr(weight),
            "activations": arr(activations),
        },
        "expected": {
            "H": arr(H),
            "L": arr(L),
            "M": arr(M),
            "ternary": iarr(ternary),
            "mask_2d": iarr(mask_2d.astype(np.int8)),
            "outlier_cols": iarr(outlier_cols),
            "outlier_vals_f16_bits": iarr(outlier_vals_f16.view(np.int16).astype(np.int32)),
            "packed_u32": iarr(packed_u32.astype(np.int64)),
            "page_scales_f16_bits": iarr(page_scales_f16.view(np.int16).astype(np.int32)),
            "lane_scales_i8": iarr(lane_scales_i8.astype(np.int64)),
        },
    }

    out_path = HERE / "septq_fixture.json"
    with open(out_path, "w") as f:
        json.dump(fixture, f, indent=2, sort_keys=True)
    size = out_path.stat().st_size
    print(f"wrote {out_path} ({size} bytes)")
    print(f"  H shape: ({in_dim}, {in_dim})")
    print(f"  ternary nnz: {int(np.count_nonzero(ternary))} / {ternary.size}")
    print(f"  mask sum:    {int(mask_2d.sum())} / {mask_2d.size}")
    print(f"  outliers:    {outlier_cols.size}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
