echo "Configuring CUDA"
cmake -B build -DCMAKE_BUILD_TYPE=Debug -DGGML_CUDA=ON -DGGML_CUDA_ENABLE_UNIFIED_MEMORY=ON -DGGML_CUDA_FORCE_MMQ=OFF -DCMAKE_CUDA_ARCHITECTURES="75" -DGGML_CUDA_FORCE_CUBLAS=OFF -DGGML_CUDA_FA_ALL_QUANTS=ON -DGGML_CUDA_F16=OFF -DGGML_BLAS=ON
echo "Configuring Vulkan"
cmake -B vulkan -DGGML_VULKAN=1 -DCMAKE_BUILD_TYPE=Debug
