import Foundation
import Security

/// Keychain-backed storage for the encrypted-volume password.
///
/// Why a separate type from ``TesseraSecretStore``: the secret store is
/// shaped around user-visible secrets that the UI reads back as a String
/// (API keys, optional tokens). The volume password is 32 random bytes
/// generated by the app and fed to `hdiutil` via stdin. We base64-encode
/// the random bytes so the stored Keychain value (and the value piped
/// to hdiutil) is always valid UTF-8. The spec calls for 32 random
/// bytes, base64-encoded (Section 6.5 of the design doc).
///
/// The account name is namespaced under `TesseraSecretStore.service`
/// (`com.tessera.studio`) so the wipe and reset paths can enumerate
/// everything the app owns if they ever need to.
public enum TesseraKeychainVolume {
    /// Account name for the volume password. The Keychain service
    /// namespace is shared with ``TesseraSecretStore`` (same bundle,
    /// same keychain access group).
    public static let volumePasswordAccount = "volume-password"

    /// Whether a volume password is currently stored. The UI uses this
    /// to decide between the "first run" and "already set up" flows.
    public static func hasVolumePassword() -> Bool {
        storedVolumePassword() != nil
    }

    /// Read the password as a String. Returns nil when nothing is
    /// stored (no volume yet) or when the Keychain entry is unreadable.
    public static func storedVolumePassword() -> String? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: TesseraSecretStore.service,
            kSecAttrAccount as String: volumePasswordAccount,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne,
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        guard status == errSecSuccess, let data = item as? Data else { return nil }
        return String(data: data, encoding: .utf8)
    }

    /// Store the volume password, overwriting any existing value.
    /// Returns true on success, false on Keychain rejection (locked
    /// keychain, missing entitlements, ...). The caller treats a
    /// false return as "not stored" rather than crashing; the volume
    /// create flow aborts cleanly in that case.
    @discardableResult
    public static func storeVolumePassword(_ password: String) -> Bool {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: TesseraSecretStore.service,
            kSecAttrAccount as String: volumePasswordAccount,
        ]
        let data = Data(password.utf8)
        let updateStatus = SecItemUpdate(
            query as CFDictionary,
            [kSecValueData as String: data] as CFDictionary
        )
        if updateStatus == errSecSuccess { return true }
        guard updateStatus == errSecItemNotFound else { return false }
        var addQuery = query
        addQuery[kSecValueData as String] = data
        addQuery[kSecAttrAccessible as String] = kSecAttrAccessibleWhenUnlockedThisDeviceOnly
        addQuery[kSecAttrSynchronizable as String] = kCFBooleanFalse
        return SecItemAdd(addQuery as CFDictionary, nil) == errSecSuccess
    }

    /// Destroy the volume password. After this returns success the
    /// Keychain no longer holds the item; subsequent reads return nil.
    /// The wipe executor calls this as its crypto-shred event (Section
    /// 7.1, step 3 in the design spec).
    ///
    /// Idempotent: `SecItemDelete` returns `errSecItemNotFound` when the
    /// entry is already gone, which we treat as success (the wipe must
    /// continue even if the key was already destroyed).
    @discardableResult
    public static func deleteVolumePassword() -> Bool {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: TesseraSecretStore.service,
            kSecAttrAccount as String: volumePasswordAccount,
        ]
        let status = SecItemDelete(query as CFDictionary)
        return status == errSecSuccess || status == errSecItemNotFound
    }

    /// Generate a fresh volume password. 32 random bytes from
    /// `SecRandomCopyBytes`, base64-encoded so the result is safe to
    /// pipe to `hdiutil -stdinpass` and safe to store as a UTF-8
    /// Keychain value. The base64 form carries the same 32*8 = 256
    /// bits of entropy as the raw bytes.
    public static func generateVolumePassword(byteCount: Int = 32) -> String? {
        var bytes = Data(count: byteCount)
        let status = bytes.withUnsafeMutableBytes { rawBuf -> Int32 in
            guard let base = rawBuf.baseAddress else { return errSecAllocate }
            return SecRandomCopyBytes(kSecRandomDefault, byteCount, base)
        }
        guard status == errSecSuccess else { return nil }
        return bytes.base64EncodedString()
    }
}
