import Foundation
import CryptoKit
import Security

/// Keychain-backed storage for the encrypted-volume password.
///
/// Why a separate type from ``TesseraSecretStore``: the secret store is
/// shaped around user-visible secrets that the UI reads back as a String
/// (API keys, optional tokens). The volume password is 32 random bytes
/// generated by the app and fed to `hdiutil` via stdin. We base64-encode
/// the random bytes so the stored Keychain value (and the value piped
/// to hdiutil) is always valid UTF-8. The spec calls for 32 random
/// bytes, base64-encoded (Section 6.5 of the design doc).
///
/// The account name is namespaced under `TesseraSecretStore.service`
/// (`com.tessera.studio`) so the wipe and reset paths can enumerate
/// everything the app owns if they ever need to.
///
/// **Receipt signing key** (per
/// `docs/tessera-productivity-foundations-design.md` §5): the
/// productivity surface uses the volume password bytes as the
/// ed25519 seed for receipt signing. Same Keychain entry, same
/// crypto-shred event (`PleadTheFifthExecutor` step 3 destroys it).
/// This is the constitutional property that makes signed receipts
/// "unverifiable after a wipe" -- the per-device key that signed
/// them is gone, so verification must fail.
public enum TesseraKeychainVolume {
    /// Account name for the volume password. The Keychain service
    /// namespace is shared with ``TesseraSecretStore`` (same bundle,
    /// same keychain access group).
    public static let volumePasswordAccount = "volume-password"

    /// Whether a volume password is currently stored. The UI uses this
    /// to decide between the "first run" and "already set up" flows.
    public static func hasVolumePassword() -> Bool {
        storedVolumePassword() != nil
    }

    /// Read the password as a String. Returns nil when nothing is
    /// stored (no volume yet) or when the Keychain entry is unreadable.
    public static func storedVolumePassword() -> String? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: TesseraSecretStore.service,
            kSecAttrAccount as String: volumePasswordAccount,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne,
        ]
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        guard status == errSecSuccess, let data = item as? Data else { return nil }
        return String(data: data, encoding: .utf8)
    }

    /// Store the volume password, overwriting any existing value.
    /// Returns true on success, false on Keychain rejection (locked
    /// keychain, missing entitlements, ...). The caller treats a
    /// false return as "not stored" rather than crashing; the volume
    /// create flow aborts cleanly in that case.
    @discardableResult
    public static func storeVolumePassword(_ password: String) -> Bool {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: TesseraSecretStore.service,
            kSecAttrAccount as String: volumePasswordAccount,
        ]
        let data = Data(password.utf8)
        let updateStatus = SecItemUpdate(
            query as CFDictionary,
            [kSecValueData as String: data] as CFDictionary
        )
        if updateStatus == errSecSuccess { return true }
        guard updateStatus == errSecItemNotFound else { return false }
        var addQuery = query
        addQuery[kSecValueData as String] = data
        addQuery[kSecAttrAccessible as String] = kSecAttrAccessibleWhenUnlockedThisDeviceOnly
        addQuery[kSecAttrSynchronizable as String] = kCFBooleanFalse
        return SecItemAdd(addQuery as CFDictionary, nil) == errSecSuccess
    }

    /// Destroy the volume password. After this returns success the
    /// Keychain no longer holds the item; subsequent reads return nil.
    /// The wipe executor calls this as its crypto-shred event (Section
    /// 7.1, step 3 in the design spec).
    ///
    /// Idempotent: `SecItemDelete` returns `errSecItemNotFound` when the
    /// entry is already gone, which we treat as success (the wipe must
    /// continue even if the key was already destroyed).
    @discardableResult
    public static func deleteVolumePassword() -> Bool {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: TesseraSecretStore.service,
            kSecAttrAccount as String: volumePasswordAccount,
        ]
        let status = SecItemDelete(query as CFDictionary)
        return status == errSecSuccess || status == errSecItemNotFound
    }

    /// Generate a fresh volume password. 32 random bytes from
    /// `SecRandomCopyBytes`, base64-encoded so the result is safe to
    /// pipe to `hdiutil -stdinpass` and safe to store as a UTF-8
    /// Keychain value. The base64 form carries the same 32*8 = 256
    /// bits of entropy as the raw bytes.
    public static func generateVolumePassword(byteCount: Int = 32) -> String? {
        var bytes = Data(count: byteCount)
        let status = bytes.withUnsafeMutableBytes { rawBuf -> Int32 in
            guard let base = rawBuf.baseAddress else { return errSecAllocate }
            return SecRandomCopyBytes(kSecRandomDefault, byteCount, base)
        }
        guard status == errSecSuccess else { return nil }
        return bytes.base64EncodedString()
    }

    // MARK: - Receipt signing key (per productivity foundations design)

    /// Derive the receipt-signing ed25519 private key from the stored
    /// volume password. The volume password is 32 random bytes
    /// (`SecRandomCopyBytes`) which is exactly the ed25519 seed size
    /// (32 bytes). We base64-decode the stored password to recover
    /// the raw bytes, then hand them to ``Curve25519/Signing/PrivateKey``
    /// via `rawRepresentation`.
    ///
    /// **Constitutional property:** the volume password lives in
    /// macOS Keychain under the same entry that
    /// ``PleadTheFifthExecutor`` step 3 (`destroy_volume_password`)
    /// destroys. Once that entry is gone, the next call to this
    /// function returns `nil` and prior signed receipts are
    /// unverifiable -- by design. There is no separate signing-key
    /// entry to forget to destroy.
    ///
    /// Returns nil when:
    /// - the volume password has not been generated yet (first run)
    /// - the Keychain entry is unreadable (locked keychain, missing
    ///   entitlements, ...)
    /// - the stored value is not valid base64
    /// - the decoded byte count is not 32 (corrupted or wrong-format
    ///   entry)
    /// - ``Curve25519/Signing/PrivateKey`` rejects the seed (should
    ///   not happen for any 32-byte input; defensive)
    public static func receiptSigningKey() -> Curve25519.Signing.PrivateKey? {
        guard let password = storedVolumePassword(),
              let rawBytes = Data(base64Encoded: password),
              rawBytes.count == 32 else {
            return nil
        }
        return try? Curve25519.Signing.PrivateKey(rawRepresentation: rawBytes)
    }

    /// Public counterpart of ``receiptSigningKey()``. The receipt
    /// store embeds the public key alongside the chain so a future
    /// verifier can check a receipt without the device's signing
    /// key. Returns nil when the signing key is unavailable.
    public static func receiptVerificationKey() -> Curve25519.Signing.PublicKey? {
        receiptSigningKey()?.publicKey
    }
}
