# CMake generated Testfile for 
# Source directory: D:/llama.cpp/tests
# Build directory: D:/llama.cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test-tokenizer-0-bert-bge]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-bert-bge.gguf")
set_tests_properties([=[test-tokenizer-0-bert-bge]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;122;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-command-r]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-command-r.gguf")
set_tests_properties([=[test-tokenizer-0-command-r]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;123;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-deepseek-coder]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-deepseek-coder.gguf")
set_tests_properties([=[test-tokenizer-0-deepseek-coder]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;124;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-deepseek-llm]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-deepseek-llm.gguf")
set_tests_properties([=[test-tokenizer-0-deepseek-llm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;125;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-falcon]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-falcon.gguf")
set_tests_properties([=[test-tokenizer-0-falcon]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;126;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-gemma-4]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-gemma-4.gguf")
set_tests_properties([=[test-tokenizer-0-gemma-4]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;127;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-gpt-2]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-gpt-2.gguf")
set_tests_properties([=[test-tokenizer-0-gpt-2]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;128;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-llama-bpe]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-llama-bpe.gguf")
set_tests_properties([=[test-tokenizer-0-llama-bpe]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;129;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-llama-spm]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-llama-spm.gguf")
set_tests_properties([=[test-tokenizer-0-llama-spm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;130;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-mpt]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-mpt.gguf")
set_tests_properties([=[test-tokenizer-0-mpt]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;131;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-phi-3]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-phi-3.gguf")
set_tests_properties([=[test-tokenizer-0-phi-3]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;132;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-qwen2]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-qwen2.gguf")
set_tests_properties([=[test-tokenizer-0-qwen2]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;133;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-qwen35]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-qwen35.gguf")
set_tests_properties([=[test-tokenizer-0-qwen35]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;134;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-refact]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-refact.gguf")
set_tests_properties([=[test-tokenizer-0-refact]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;135;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-starcoder]=] "D:/llama.cpp/bin/test-tokenizer-0.exe" "D:/llama.cpp/models/ggml-vocab-starcoder.gguf")
set_tests_properties([=[test-tokenizer-0-starcoder]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;136;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat-peg-parser]=] "D:/llama.cpp/bin/test-chat-peg-parser.exe")
set_tests_properties([=[test-chat-peg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;232;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-jinja]=] "D:/llama.cpp/bin/test-jinja.exe")
set_tests_properties([=[test-jinja]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;233;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-jinja-py]=] "D:/llama.cpp/bin/test-jinja.exe" "-py")
set_tests_properties([=[test-jinja-py]=] PROPERTIES  LABELS "python" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;40;add_test;D:/llama.cpp/tests/CMakeLists.txt;234;llama_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat-auto-parser]=] "D:/llama.cpp/bin/test-chat-auto-parser.exe")
set_tests_properties([=[test-chat-auto-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "D:/llama.cpp" _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;235;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat-template]=] "D:/llama.cpp/bin/test-chat-template.exe")
set_tests_properties([=[test-chat-template]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;236;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-log]=] "D:/llama.cpp/bin/test-log.exe")
set_tests_properties([=[test-log]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;237;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-peg-parser]=] "D:/llama.cpp/bin/test-peg-parser.exe")
set_tests_properties([=[test-peg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;238;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-download-model]=] "C:/Program Files/Microsoft Visual Studio/18/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" "-DDEST=D:/llama.cpp/tinyllamas/stories15M-q4_0.gguf" "-DNAME=tinyllamas/stories15M-q4_0.gguf" "-DHASH=SHA256=66967fbece6dbe97886593fdbb73589584927e29119ec31f08090732d1861739" "-P" "D:/llama.cpp/cmake/download-models.cmake")
set_tests_properties([=[test-download-model]=] PROPERTIES  FIXTURES_SETUP "test-download-model" _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;259;add_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-thread-safety]=] "D:/llama.cpp/bin/test-thread-safety.exe" "-m" "D:/llama.cpp/tinyllamas/stories15M-q4_0.gguf" "-ngl" "99" "-p" "The meaning of life is" "-n" "128" "-c" "256" "-ub" "32" "-np" "4" "-t" "2")
set_tests_properties([=[test-thread-safety]=] PROPERTIES  FIXTURES_REQUIRED "test-download-model" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;267;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-arg-parser]=] "D:/llama.cpp/bin/test-arg-parser.exe")
set_tests_properties([=[test-arg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;270;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-model-resolution]=] "D:/llama.cpp/bin/test-model-resolution.exe")
set_tests_properties([=[test-model-resolution]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;271;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-opt]=] "D:/llama.cpp/bin/test-opt.exe")
set_tests_properties([=[test-opt]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;277;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-backend-ops]=] "D:/llama.cpp/bin/test-backend-ops.exe")
set_tests_properties([=[test-backend-ops]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;279;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-model-load-cancel]=] "D:/llama.cpp/bin/test-model-load-cancel.exe")
set_tests_properties([=[test-model-load-cancel]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;281;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-autorelease]=] "D:/llama.cpp/bin/test-autorelease.exe")
set_tests_properties([=[test-autorelease]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;282;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-backend-sampler]=] "D:/llama.cpp/bin/test-backend-sampler.exe")
set_tests_properties([=[test-backend-sampler]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;283;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-state-restore-fragmented]=] "D:/llama.cpp/bin/test-state-restore-fragmented.exe" "-m" "D:/llama.cpp/tinyllamas/stories15M-q4_0.gguf")
set_tests_properties([=[test-state-restore-fragmented]=] PROPERTIES  FIXTURES_REQUIRED "test-download-model" LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;287;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-save-load-state]=] "D:/llama.cpp/bin/test-save-load-state.exe" "-m" "D:/llama.cpp/tinyllamas/stories15M-q4_0.gguf")
set_tests_properties([=[test-save-load-state]=] PROPERTIES  FIXTURES_REQUIRED "test-download-model" LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;291;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-barrier]=] "D:/llama.cpp/bin/test-barrier.exe")
set_tests_properties([=[test-barrier]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;300;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-quantize-fns]=] "D:/llama.cpp/bin/test-quantize-fns.exe")
set_tests_properties([=[test-quantize-fns]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;301;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-quantize-perf]=] "D:/llama.cpp/bin/test-quantize-perf.exe")
set_tests_properties([=[test-quantize-perf]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;302;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-rope]=] "D:/llama.cpp/bin/test-rope.exe")
set_tests_properties([=[test-rope]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;303;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-col2im-1d]=] "D:/llama.cpp/bin/test-col2im-1d.exe")
set_tests_properties([=[test-col2im-1d]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;304;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-mtmd-c-api]=] "D:/llama.cpp/bin/test-mtmd-c-api.exe")
set_tests_properties([=[test-mtmd-c-api]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;309;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-gguf]=] "D:/llama.cpp/bin/test-gguf.exe")
set_tests_properties([=[test-gguf]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;341;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-alloc]=] "D:/llama.cpp/bin/test-alloc.exe")
set_tests_properties([=[test-alloc]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/llama.cpp/tests/CMakeLists.txt;110;add_test;D:/llama.cpp/tests/CMakeLists.txt;344;llama_build_and_test;D:/llama.cpp/tests/CMakeLists.txt;0;")
