#!/usr/bin/env python3
"""Smoke + e2e tests for tools/tessera/runtime_probe.py.

Run as a standalone script. Exits 0 on success, non-zero on
failure. Two test sections:

  1. Synthetic-logits (no llama-cli needed): write a v3 TPMO
     matmul-output sidecar directly to disk for the BF16 "source"
     and a slightly-perturbed version for the "quantized"
     model, then run join_sidecars + aggregate + JSONL writer
     and verify the four metrics match the expected analytical
     values.

  2. End-to-end (requires llama-cli built with the
     --tessera-matmul-output-dir support): run a tiny synthetic
     model through llama-cli twice, run runtime_probe against
     the resulting sidecar directories, and verify the JSONL
     report has the expected schema and at least one
     per-tensor aggregate.

The test uses a tiny on-the-fly F16 model that fits in <100 MB
of RAM and a 32-token prefill to keep the e2e section fast. The
synthetic model is generated by dequantizing a Q4_0 model back
to F16 and writing it as a new GGUF (the inverse of the standard
quantize step); the BF16 source IS the dequantized F16, and the
"quantized" model is a Q4_0 of the same.

Usage::

    python3 tools/tessera/test_l2_forward.py [--llama-cli PATH]
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import struct
import sys
import tempfile
from pathlib import Path
from typing import List

import numpy as np

# Make runtime_probe importable when this script is run from the
# tools/tessera/ directory or from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools" / "tessera"))
import runtime_probe  # noqa: E402


# ---------------------------------------------------------------------------
# Synthetic-sidecar helpers (no llama-cli needed)
# ---------------------------------------------------------------------------

def write_synthetic_sidecar(
    path: str,
    tensor_name: str,
    rows: int,
    cols: int,
    data: np.ndarray,
    total_samples: int | None = None,
) -> None:
    """Write a v3 TPMO .matmul-output.f32 sidecar file. Mirrors
    the on-disk layout of the C++ sidecar (see
    tessera-matmul-output.h)."""
    if total_samples is None:
        total_samples = int(data.shape[0])
    n_floats = data.size
    if data.size != rows * cols:
        rows = data.shape[0]
    with open(path, "wb") as f:
        f.write(b"TPMO")
        f.write(struct.pack("<I", 3))                    # version
        f.write(struct.pack("<q", rows))                  # rows
        f.write(struct.pack("<q", cols))                  # cols
        f.write(struct.pack("<I", 0))                    # dtype = F32
        f.write(struct.pack("<f", 0.0))                  # threshold (unused)
        f.write(struct.pack("<q", total_samples))         # total_samples
        f.write(np.full(rows, 1, dtype=np.int32).tobytes())  # row_samples
        f.write(b"\x00" * (24 * rows))                    # v3 per-row meta
        f.write(np.ascontiguousarray(data, dtype=np.float32).tobytes())


def test_synthetic_metrics() -> bool:
    """Verify the four L2 divergence metrics on a hand-computed
    case. The synthetic BF16 logits are a known distribution;
    the "quantized" logits add a known perturbation; we check
    the metrics match the analytical formulas."""
    print("--- synthetic metrics ---", flush=True)
    cols = 32
    n_positions = 4
    rng = np.random.default_rng(0xC0FFEE)

    bf16 = np.zeros((n_positions, cols), dtype=np.float32)
    for pos, peak in enumerate([0, 5, 12, 20]):
        bf16[pos, peak] = 10.0
        bf16[pos] += rng.normal(0, 0.1, size=cols).astype(np.float32)

    quant = bf16.copy()
    quant[0] = bf16[0] + rng.normal(0, 0.05, size=cols).astype(np.float32)
    quant[1, 5] -= 5.0
    quant[1, 6] += 5.5
    quant[2] = bf16[2] + rng.normal(0, 0.05, size=cols).astype(np.float32)
    quant[3] = bf16[3] + rng.normal(0, 0.05, size=cols).astype(np.float32)

    for pos in range(n_positions):
        div = runtime_probe.per_tensor_divergence(bf16[pos], quant[pos])
        diff = bf16[pos].astype(np.float64) - quant[pos].astype(np.float64)
        ref_max = float(np.max(np.abs(diff)))
        ref_mean = float(np.mean(np.abs(diff)))
        ref_rel = float(np.sum(diff ** 2)) / float(np.sum(bf16[pos].astype(np.float64) ** 2))
        if not (abs(div["max_abs"] - ref_max) < 1e-6):
            print(f"FAIL pos={pos} max_abs: got {div['max_abs']}, ref {ref_max}", file=sys.stderr)
            return False
        if not (abs(div["mean_abs"] - ref_mean) < 1e-6):
            print(f"FAIL pos={pos} mean_abs: got {div['mean_abs']}, ref {ref_mean}", file=sys.stderr)
            return False
        if not (abs(div["relative_frobenius"] - ref_rel) < 1e-6):
            print(f"FAIL pos={pos} rel_frob: got {div['relative_frobenius']}, ref {ref_rel}", file=sys.stderr)
            return False

    div1 = runtime_probe.per_tensor_divergence(bf16[1], quant[1])
    if div1["top1_mismatch"] != 1:
        print(f"FAIL pos=1 expected top1_mismatch=1, got {div1['top1_mismatch']}", file=sys.stderr)
        return False
    for pos in (0, 2, 3):
        divp = runtime_probe.per_tensor_divergence(bf16[pos], quant[pos])
        if divp["top1_mismatch"] != 0:
            print(f"FAIL pos={pos} expected top1_mismatch=0, got {divp['top1_mismatch']}", file=sys.stderr)
            return False

    with tempfile.TemporaryDirectory() as tmp:
        bf16_dir = os.path.join(tmp, "bf16")
        quant_dir = os.path.join(tmp, "quant")
        os.makedirs(bf16_dir)
        os.makedirs(quant_dir)
        name = "blk.0.attn_q.weight"
        write_synthetic_sidecar(
            os.path.join(bf16_dir, name + ".matmul-output.f32"),
            name, n_positions, cols, bf16,
        )
        write_synthetic_sidecar(
            os.path.join(quant_dir, name + ".matmul-output.f32"),
            name, n_positions, cols, quant,
        )

        records = list(runtime_probe.join_sidecars(bf16_dir, quant_dir))
        if len(records) != n_positions:
            print(f"FAIL join_sidecars: expected {n_positions} records, got {len(records)}", file=sys.stderr)
            return False
        for rec in records:
            if rec["tensor"] != name:
                print(f"FAIL: bad tensor name in record: {rec['tensor']}", file=sys.stderr)
                return False
            if rec["layer"] != 0:
                print(f"FAIL: bad layer in record: {rec['layer']}", file=sys.stderr)
                return False
            pos = rec["position"]
            ref = runtime_probe.per_tensor_divergence(bf16[pos], quant[pos])
            for k in ("max_abs", "mean_abs", "relative_frobenius", "top1_mismatch", "top5_mismatch"):
                if rec["divergence"][k] != ref[k]:
                    print(f"FAIL pos={pos} {k}: got {rec['divergence'][k]}, ref {ref[k]}", file=sys.stderr)
                    return False

        aggs = list(runtime_probe.aggregate_per_tensor(records))
        if len(aggs) != 1:
            print(f"FAIL aggregate: expected 1 tensor, got {len(aggs)}", file=sys.stderr)
            return False
        agg = aggs[0]
        if agg["n_positions"] != n_positions:
            print(f"FAIL aggregate n_positions: {agg['n_positions']}", file=sys.stderr)
            return False
        ref_max = max(r["divergence"]["max_abs"] for r in records)
        if abs(agg["divergence"]["max_abs"] - ref_max) > 1e-6:
            print(f"FAIL aggregate max_abs: {agg['divergence']['max_abs']} vs {ref_max}", file=sys.stderr)
            return False
        ref_mean = sum(r["divergence"]["mean_abs"] for r in records) / n_positions
        if abs(agg["divergence"]["mean_abs"] - ref_mean) > 1e-6:
            print(f"FAIL aggregate mean_abs: {agg['divergence']['mean_abs']} vs {ref_mean}", file=sys.stderr)
            return False
        if abs(agg["divergence"]["top1_mismatch_rate"] - 0.25) > 1e-6:
            print(f"FAIL aggregate top1_mismatch_rate: {agg['divergence']['top1_mismatch_rate']}", file=sys.stderr)
            return False

        out_path = os.path.join(tmp, "report.jsonl")
        runtime_probe.write_jsonl_report(
            out_path=out_path,
            bf16_invocation={"cmd": ["synthetic"], "returncode": 0, "duration_s": 0.0},
            quant_invocation={"cmd": ["synthetic"], "returncode": 0, "duration_s": 0.0},
            bf16_model="synthetic-bf16",
            quant_model="synthetic-quant",
            prompts_file="<synthetic>",
            n_tokens=0,
            n_ctx=32,
            stride=1,
            per_position_records=records,
            per_tensor_aggregates=aggs,
        )
        with open(out_path) as f:
            lines = f.readlines()
        if len(lines) != 1 + n_positions + 1:
            print(f"FAIL jsonl line count: {len(lines)}", file=sys.stderr)
            return False
        prov = json.loads(lines[0])
        if prov["record_type"] != "provenance":
            print(f"FAIL jsonl prov record_type: {prov['record_type']}", file=sys.stderr)
            return False
        if prov["schema"] != "llama.tessera.runtime-probe.v1":
            print(f"FAIL jsonl prov schema: {prov['schema']}", file=sys.stderr)
            return False
        for i in range(n_positions):
            r = json.loads(lines[1 + i])
            if r["record_type"] != "per_position":
                print(f"FAIL jsonl per_position record_type: {r['record_type']}", file=sys.stderr)
                return False
        agg_line = json.loads(lines[-1])
        if agg_line["record_type"] != "tensor_aggregate":
            print(f"FAIL jsonl aggregate record_type: {agg_line['record_type']}", file=sys.stderr)
            return False
    print("ok   synthetic metrics", flush=True)
    return True


def test_end_to_end(llama_cli: str) -> bool:
    """Run the orchestrator against a real llama-cli invocation
    on the qwen 0.5B Q4_K_M (the same model used for both BF16
    "source" and "quantized" since no F16 is locally available;
    the e2e verifies the orchestrator produces a valid report,
    not that there is meaningful divergence)."""
    print("--- end-to-end (real llama-cli) ---", flush=True)
    if not os.path.exists(llama_cli):
        print(f"SKIP: llama-cli not found at {llama_cli}", file=sys.stderr)
        return True
    model_q4km = os.path.expanduser(
        "~/Library/Application Support/qwen2.5-0.5b-instruct-q4_k_m.gguf"
    )
    if not os.path.exists(model_q4km):
        print(f"SKIP: qwen2.5-0.5b Q4_K_M not found at {model_q4km}", file=sys.stderr)
        return True
    bf16_model = model_q4km
    quant_model = model_q4km

    with tempfile.TemporaryDirectory() as tmp:
        prompts = os.path.join(tmp, "prompts.txt")
        sentence = (
            "The quick brown fox jumps over the lazy dog. "
            "In a hole in the ground there lived a hobbit. "
            "It was the best of times, it was the worst of times. "
        )
        with open(prompts, "w") as f:
            for _ in range(4):
                f.write(sentence * 4 + "\n")

        bf16_dir = os.path.join(tmp, "bf16")
        quant_dir = os.path.join(tmp, "quant")
        out_path = os.path.join(tmp, "report.jsonl")

        rc = runtime_probe.main([
            "--bf16", bf16_model,
            "--quantized", quant_model,
            "--prompts", prompts,
            "--bf16-out-dir", bf16_dir,
            "--quantized-out-dir", quant_dir,
            "--out", out_path,
            "--llama-cli", llama_cli,
            "--n-tokens", "4",
            "--n-ctx", "512",
        ])
        if rc != 0:
            print(f"FAIL: runtime_probe.main returned {rc}", file=sys.stderr)
            return False
        if not os.path.exists(out_path):
            print(f"FAIL: output report {out_path} not created", file=sys.stderr)
            return False
        with open(out_path) as f:
            lines = f.readlines()
        if not lines:
            print("FAIL: report is empty", file=sys.stderr)
            return False
        prov = json.loads(lines[0])
        if prov["schema"] != "llama.tessera.runtime-probe.v1":
            print(f"FAIL: schema mismatch: {prov['schema']}", file=sys.stderr)
            return False
        if prov["record_type"] != "provenance":
            print(f"FAIL: first line is not provenance: {prov['record_type']}", file=sys.stderr)
            return False
        n_position = sum(1 for ln in lines[1:]
                         if json.loads(ln).get("record_type") == "per_position")
        if n_position < 1:
            print(f"FAIL: no per-position records in {out_path}", file=sys.stderr)
            return False
        n_agg = sum(1 for ln in lines[1:]
                    if json.loads(ln).get("record_type") == "tensor_aggregate")
        if n_agg < 1:
            print(f"FAIL: no per-tensor aggregate in {out_path}", file=sys.stderr)
            return False
        print(f"ok   e2e: {n_position} per-position + {n_agg} aggregates", flush=True)
    return True


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--llama-cli", default="./build/bin/llama-cli",
                   help="Path to the llama-cli binary (e2e section is skipped if missing).")
    args = p.parse_args(argv)
    ok = True
    if not test_synthetic_metrics():
        ok = False
    if not test_end_to_end(args.llama_cli):
        ok = False
    if ok:
        print("PASS", flush=True)
        return 0
    print("FAIL", file=sys.stderr, flush=True)
    return 1


if __name__ == "__main__":
    sys.exit(main())
