export const SETTING_CONFIG_DEFAULT: Record<string, string | number | boolean> = {
	// Note: in order not to introduce breaking changes, please keep the same data type (number, string, etc) if you want to change the default value. Do not use null or undefined for default value.
	// Do not use nested objects, keep it single level. Prefix the key if you need to group them.
	apiKey: '',
	systemMessage: '',
	showSystemMessage: true,
	theme: 'system',
	showThoughtInProgress: false,
	showToolCalls: false,
	disableReasoningFormat: false,
	keepStatsVisible: false,
	showMessageStats: true,
	askForTitleConfirmation: false,
	pasteLongTextToFileLen: 2500,
	copyTextAttachmentsAsPlainText: false,
	pdfAsImage: false,
	disableAutoScroll: false,
	renderUserContentAsMarkdown: false,
	alwaysShowSidebarOnDesktop: false,
	autoShowSidebarOnNewChat: true,
	autoMicOnEmpty: false,
	// make sure these default values are in sync with `common.h`
	samplers: 'top_k;typ_p;top_p;min_p;temperature',
	backend_sampling: false,
	temperature: 0.8,
	dynatemp_range: 0.0,
	dynatemp_exponent: 1.0,
	top_k: 40,
	top_p: 0.95,
	min_p: 0.05,
	xtc_probability: 0.0,
	xtc_threshold: 0.1,
	typ_p: 1.0,
	repeat_last_n: 64,
	repeat_penalty: 1.0,
	presence_penalty: 0.0,
	frequency_penalty: 0.0,
	dry_multiplier: 0.0,
	dry_base: 1.75,
	dry_allowed_length: 2,
	dry_penalty_last_n: -1,
	max_tokens: -1,
	custom: '', // custom json-stringified object
	// experimental features
	pyInterpreterEnabled: false,
	enableContinueGeneration: false
};

export const SETTING_CONFIG_INFO: Record<string, string> = {
	apiKey: 'chat.settings.help.api_key',
	systemMessage: 'chat.settings.help.system_message',
	showSystemMessage: 'chat.settings.help.show_system_message',
	theme: 'chat.settings.help.theme',
	pasteLongTextToFileLen: 'chat.settings.help.paste_long_text_to_file_length',
	copyTextAttachmentsAsPlainText: 'chat.settings.help.copy_text_attachments_as_plain_text',
	samplers: 'chat.settings.help.samplers',
	backend_sampling: 'chat.settings.help.backend_sampling',
	temperature: 'chat.settings.help.temperature',
	dynatemp_range: 'chat.settings.help.dynamic_temperature_range',
	dynatemp_exponent: 'chat.settings.help.dynamic_temperature_exponent',
	top_k: 'chat.settings.help.top_k',
	top_p: 'chat.settings.help.top_p',
	min_p: 'chat.settings.help.min_p',
	xtc_probability: 'chat.settings.help.xtc_probability',
	xtc_threshold: 'chat.settings.help.xtc_threshold',
	typ_p: 'chat.settings.help.typical_p',
	repeat_last_n: 'chat.settings.help.repeat_last_n',
	repeat_penalty: 'chat.settings.help.repeat_penalty',
	presence_penalty: 'chat.settings.help.presence_penalty',
	frequency_penalty: 'chat.settings.help.frequency_penalty',
	dry_multiplier: 'chat.settings.help.dry_multiplier',
	dry_base: 'chat.settings.help.dry_base',
	dry_allowed_length: 'chat.settings.help.dry_allowed_length',
	dry_penalty_last_n: 'chat.settings.help.dry_penalty_last_n',
	max_tokens: 'chat.settings.help.max_tokens',
	custom: 'chat.settings.help.custom_json',
	showThoughtInProgress: 'chat.settings.help.show_thought_in_progress',
	showToolCalls: 'chat.settings.help.show_tool_calls',
	disableReasoningFormat: 'chat.settings.help.show_raw_llm_output',
	keepStatsVisible: 'chat.settings.help.keep_stats_visible',
	showMessageStats: 'chat.settings.help.show_message_stats',
	askForTitleConfirmation: 'chat.settings.help.ask_for_title_confirmation',
	pdfAsImage: 'chat.settings.help.parse_pdf_as_image',
	disableAutoScroll: 'chat.settings.help.disable_auto_scroll',
	renderUserContentAsMarkdown: 'chat.settings.help.render_user_content_as_markdown',
	alwaysShowSidebarOnDesktop: 'chat.settings.help.always_show_sidebar_on_desktop',
	autoShowSidebarOnNewChat: 'chat.settings.help.auto_show_sidebar_on_new_chat',
	autoMicOnEmpty: 'chat.settings.help.show_microphone_on_empty',
	pyInterpreterEnabled: 'chat.settings.help.py_interpreter_enabled',
	enableContinueGeneration: 'chat.settings.help.enable_continue_generation'
};
