import SwiftUI
import TesseraCore

/// The drafter-training surface of the Learning dashboard: trace progress
/// toward the training gate, an explicit validate/train action pair with
/// live driver progress and cancel, and the honest record of the last
/// cycle. Reads the shared orchestrator; never fabricates state.
struct LearningTrainingSection: View {
    /// Regenerated by the dashboard's Refresh button; the section reloads
    /// its read-only state without touching any in-flight run task.
    let refreshID: UUID

    @Environment(\.openSettings) private var openSettings

    @State private var record: TesseraTrainingOrchestrator.TrainingRecord?
    @State private var traceCount = 0
    @State private var capture = TesseraRuntimeCaptureSummary()
    @State private var curationCounts = TesseraCurationCounts()
    @State private var quarantinedSessions: [TesseraQuarantinedSessionInfo] = []
    @State private var pendingPurgeSid: String?
    @State private var minTraces = TesseraSettingsDefault.learningMinTracesForTraining
    @State private var baseModel = ""
    @State private var binaryPath = ""
    @State private var binaryOK = false
    @State private var dryRunConfigured = true
    @State private var autoTrain = TesseraSettingsDefault.learningAutoTrain
    @State private var running = false
    @State private var runningDry = false
    @State private var liveLine: String?
    @State private var runTask: Task<Void, Never>?

    var body: some View {
        Section("Drafter Training") {
            traceGaugeRow
            runtimeCaptureRow
            if !quarantinedSessions.isEmpty {
                quarantineList
            }
            if !setupComplete {
                setupRow
            } else if running {
                runningRow
            } else {
                actionRow
                idleCaption
                if let record {
                    recordRows(record)
                } else {
                    Text("No training cycle has run yet.")
                        .foregroundStyle(.secondary)
                }
            }
        }
        .confirmationDialog(
            "Purge this session?",
            isPresented: Binding(
                get: { pendingPurgeSid != nil },
                set: { if !$0 { pendingPurgeSid = nil } }),
            titleVisibility: .visible
        ) {
            Button("Purge session", role: .destructive) {
                if let sid = pendingPurgeSid {
                    purgeSession(sid: sid)
                }
                pendingPurgeSid = nil
            }
        } message: {
            Text("The session's captured records are permanently deleted from this Mac. This cannot be undone.")
        }
        .onAppear { load() }
        .onChange(of: refreshID) { load() }
    }

    // MARK: - Rows

    private var traceGaugeRow: some View {
        VStack(alignment: .leading, spacing: 4) {
            LabeledContent("training traces") {
                Text("\(traceCount.formatted()) of \(minTraces.formatted())")
                    .monospacedDigit()
            }
            Gauge(
                value: Double(min(traceCount, minTraces)),
                in: 0...Double(max(minTraces, 1))
            ) {
                EmptyView()
            } currentValueLabel: {
                EmptyView()
            }
            .tint(traceCount >= minTraces ? .green : .accentColor)
            .accessibilityLabel("Training trace progress")
            .accessibilityValue("\(traceCount) of \(minTraces) traces")
        }
        .padding(.vertical, 2)
    }

    /// Runtime capture status (runtime-traces spec section 10): this
    /// session's record count, the lifetime runtime record total, the live
    /// acceptance rate across captured steps, and the curation state
    /// (promoted / quarantined / pending session counts). Read-only.
    private var runtimeCaptureRow: some View {
        VStack(alignment: .leading, spacing: 4) {
            LabeledContent("runtime capture") {
                Text(runtimeCaptureSummary).monospacedDigit()
            }
            if let rate = capture.acceptanceRate {
                Gauge(value: rate, in: 0...1) {
                    EmptyView()
                } currentValueLabel: {
                    EmptyView()
                }
                .tint(.accentColor)
                .accessibilityLabel("Runtime acceptance rate")
                .accessibilityValue(rate.formatted(.percent))
            }
        }
        .padding(.vertical, 2)
    }

    private var runtimeCaptureSummary: String {
        let sessions = capture.sessions.count
        guard capture.totalRecords > 0 else {
            return sessions == 0 ? "no runtime records yet" : "\(sessions) session(s), 0 records"
        }
        var parts: [String] = []
        if let latest = capture.latestSession {
            parts.append("latest session \(latest.records) rec")
        }
        parts.append("\(capture.totalRecords) total")
        if let rate = capture.acceptanceRate {
            parts.append("\(rate.formatted(.percent.precision(.fractionLength(0)))) accepted")
        }
        parts.append(curationStateSummary)
        return parts.joined(separator: " · ")
    }

    /// Curation state for the capture row (runtime-traces spec section 10):
    /// promoted / quarantined / pending session counts.
    private var curationStateSummary: String {
        "\(curationCounts.promoted) promoted · "
            + "\(curationCounts.quarantined) quarantined · "
            + "\(curationCounts.pending) pending"
    }

    /// The quarantine list (runtime-traces spec section 10): session date,
    /// token count, and the probe class that quarantined it - never the
    /// matched content. Purge uses the app's destructive-confirmation
    /// pattern (the confirmationDialog attached to the section).
    private var quarantineList: some View {
        DisclosureGroup("Quarantined sessions (\(quarantinedSessions.count))") {
            ForEach(quarantinedSessions) { session in
                HStack(alignment: .firstTextBaseline, spacing: 8) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text(session.date?.formatted(date: .abbreviated, time: .shortened) ?? "unknown date")
                        Text("\(session.tokenCount.formatted()) tokens · \(session.probeClasses.joined(separator: ", "))")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    Spacer()
                    Button("Purge", role: .destructive) {
                        pendingPurgeSid = session.sid
                    }
                    .controlSize(.small)
                    .help("Permanently delete this session's captured records")
                }
                .padding(.vertical, 2)
            }
            Text("Quarantined sessions stay local and never enter training; only purge removes them.")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .help("Sessions a sensitivity probe quarantined; listed by date, token count, and probe class only")
    }

    private var setupComplete: Bool {
        !baseModel.isEmpty && binaryOK
    }

    private var setupRow: some View {
        VStack(alignment: .leading, spacing: 6) {
            Label("Training is not set up yet.", systemImage: "slider.horizontal.3")
            Text(setupDetail)
                .foregroundStyle(.secondary)
                .font(.callout)
            Button("Open Learning Settings") { openSettings() }
                .help("Opens Settings, where the drafter model and training driver are configured")
        }
        .padding(.vertical, 2)
    }

    /// Names exactly what is missing, so the setup wall has a visible door.
    private var setupDetail: String {
        var missing: [String] = []
        if baseModel.isEmpty {
            missing.append("No drafter model (GGUF) is configured.")
        }
        if !binaryOK {
            missing.append("tessera-train-lk was not found at \(binaryPath).")
        }
        return missing.joined(separator: " ")
    }

    private var runningRow: some View {
        HStack(spacing: 10) {
            ProgressView()
                .controlSize(.small)
            VStack(alignment: .leading, spacing: 2) {
                Text(runningDry ? "Validating training setup…" : "Training drafter…")
                if let liveLine {
                    Text(liveLine)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .monospacedDigit()
                }
            }
            Spacer()
            Button("Cancel", role: .cancel) {
                runTask?.cancel()
            }
            .help("Stop this training cycle; partial work is discarded")
        }
        .padding(.vertical, 2)
    }

    private var actionRow: some View {
        HStack(spacing: 10) {
            Button("Validate Setup") { start(dryRun: true) }
                .help("Build and validate the training dataset without training (--dry-run)")
            Button("Train Drafter") { start(dryRun: false) }
                .buttonStyle(.borderedProminent)
                .help("Train the drafter on the accumulated traces and save the result")
            Spacer()
        }
        .padding(.vertical, 2)
    }

    private var idleCaption: some View {
        Group {
            if dryRunConfigured {
                Text("Dry run is on in Settings: idle sweeps validate the dataset only and never write a trained drafter.")
            } else if autoTrain {
                Text("Idle sweeps train automatically on power every \(TesseraSettings.learningTrainingIntervalHours) hours.")
            } else {
                Text("Idle training is off; cycles run only from this button or the run_training tool.")
            }
        }
        .font(.caption)
        .foregroundStyle(.secondary)
    }

    @ViewBuilder
    private func recordRows(_ record: TesseraTrainingOrchestrator.TrainingRecord) -> some View {
        LabeledContent("last cycle") {
            Label(outcomeTitle(record.outcome), systemImage: outcomeSymbol(record.outcome))
                .foregroundStyle(outcomeTint(record.outcome))
        }
        LabeledContent("when", value: record.timestamp.formatted())
        if let drafter = record.drafterPath, !drafter.isEmpty {
            LabeledContent("drafter") {
                Text(drafter).textSelection(.enabled).lineLimit(1).truncationMode(.middle)
            }
        }
        Text(record.note)
            .font(.callout)
            .foregroundStyle(.secondary)
            .textSelection(.enabled)
        if let stderr = record.stderr, !stderr.isEmpty {
            DisclosureGroup("Driver output") {
                Text(stderr)
                    .font(.caption.monospaced())
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .help("The tail of the training driver's stderr for this cycle")
        }
    }

    // MARK: - Outcome display (symbol carries the meaning, color reinforces)

    private func outcomeTitle(_ outcome: TesseraTrainingOrchestrator.TrainingOutcome) -> String {
        switch outcome {
        case .trainingCompleted: "Training complete"
        case .dryRun: "Validated (dry run)"
        case .trainingFailed: "Training failed"
        case .skippedInsufficientTraces: "Skipped: not enough traces"
        case .skippedNoModel: "Skipped: no drafter model"
        case .guardPassed: "Guard passed"
        case .guardFailed: "Guard failed"
        }
    }

    private func outcomeSymbol(_ outcome: TesseraTrainingOrchestrator.TrainingOutcome) -> String {
        switch outcome {
        case .trainingCompleted: "checkmark.seal.fill"
        case .dryRun: "checkmark.circle"
        case .trainingFailed: "xmark.octagon.fill"
        case .skippedInsufficientTraces, .skippedNoModel: "pause.circle"
        case .guardPassed: "checkmark.shield"
        case .guardFailed: "xmark.shield"
        }
    }

    private func outcomeTint(_ outcome: TesseraTrainingOrchestrator.TrainingOutcome) -> Color {
        switch outcome {
        case .trainingCompleted, .dryRun, .guardPassed: .green
        case .trainingFailed, .guardFailed: .red
        case .skippedInsufficientTraces, .skippedNoModel: .orange
        }
    }

    // MARK: - Actions

    private func start(dryRun: Bool) {
        guard !running, let orchestrator = TesseraLearningCenter.shared.training else { return }
        running = true
        runningDry = dryRun
        liveLine = nil
        runTask = Task {
            for await event in orchestrator.runStreaming(overrideDryRun: dryRun) {
                switch event {
                case .starting(let count, _):
                    liveLine = "\(count.formatted()) trace(s) staged"
                case .datasetBuilt(let examples, let memoryMiB):
                    liveLine = "dataset: \(examples.formatted()) examples (~\(memoryMiB.formatted(.number.precision(.fractionLength(0)))) MiB)"
                case .epoch(let index, let loss, let agreement):
                    liveLine = "epoch \(index): loss \(loss.formatted(.number.precision(.fractionLength(4)))), agreement \(agreement.formatted(.number.precision(.fractionLength(4))))"
                case .finished(let finished):
                    record = finished
                    TrainingNotifier.post(record: finished)
                }
            }
            running = false
            runTask = nil
            load()
        }
    }

    // MARK: - Loading

    private func load() {
        let orchestrator = TesseraLearningCenter.shared.training
        record = orchestrator?.lastTraining()
        traceCount = orchestrator?.traceStore.totalRecords() ?? 0
        let store = orchestrator?.traceStore ?? TesseraTraceStore()
        capture = store.runtimeSummary()
        let ledger = TesseraCurationLedger.forStore(store)
        curationCounts = ledger.curationCounts(
            sessionSids: Set(capture.sessions.map { $0.sid }))
        quarantinedSessions = ledger.quarantinedSessionInfos()
        minTraces = TesseraSettings.learningMinTracesForTraining
        baseModel = TesseraSettings.learningBaseModelPath
        dryRunConfigured = TesseraSettings.learningTrainingDryRun
        autoTrain = TesseraSettings.learningAutoTrain
        binaryPath = TesseraTrainBinaryResolver.resolve(override: TesseraSettings.learningTrainBinary)
        binaryOK = FileManager.default.isExecutableFile(atPath: binaryPath)
    }

    // MARK: - Quarantine purge

    /// User-initiated purge (spec section 12.4): remove the session's
    /// runtime records from the store and record the purge verdict so it
    /// leaves the quarantine list and is never re-analyzed. Only reached
    /// through the destructive-confirmation dialog.
    private func purgeSession(sid: String) {
        guard let store = TesseraLearningCenter.shared.training?.traceStore else { return }
        do {
            try store.purgeSession(sid: sid)
            try TesseraCurationLedger.forStore(store).markPurged(sid: sid)
        } catch {
            print("[tessera.curation] purge failed for \(sid): \(error.localizedDescription)")
        }
        load()
    }
}
