import {
	readFileSync,
	writeFileSync,
	existsSync,
	readdirSync,
	copyFileSync,
	rmSync
} from 'node:fs';
import { execSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Plugin } from 'vite';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GUIDE_FOR_FRONTEND = `
<!--
  This is a static build of the frontend.
  It is automatically generated by the build process.
  Do not edit this file directly.
  To make changes, refer to the "Web UI" section in the README.
-->
`.trim();

const OUTPUT_DIR = process.env.LLAMA_UI_OUT_DIR ?? './dist';
let processed = false;

export function llamaCppBuildPlugin(): Plugin {
	return {
		name: 'llamacpp:build',
		apply: 'build',
		closeBundle() {
			setTimeout(() => {
				try {
					if (processed) return;
					processed = true;

					// Build version: explicit env var (from CMake) > git hash > fallback
					let buildVersion = process.env.LLAMA_UI_VERSION;
					if (!buildVersion || buildVersion.trim() === '') {
						try {
							const gitHash = execSync('git rev-parse --short HEAD', {
								cwd: resolve(__dirname, '../..'),
								encoding: 'utf-8'
							}).trim();
							const epoch = Math.floor(Date.now() / 1000);
							buildVersion = `${gitHash}-${epoch}`;
						} catch {
							buildVersion = `fallback-${Date.now()}`;
						}
					}

					const outDir = resolve(OUTPUT_DIR);
					const indexPath = resolve(outDir, 'index.html');
					if (!existsSync(indexPath)) return;

					let content = readFileSync(indexPath, 'utf-8');

					content = content.replace(/\r/g, '');
					content = GUIDE_FOR_FRONTEND + '\n' + content;

					// Keep the Vite hash as a query string so each build busts the browser cache
					content = content.replace(/\/_app\/immutable\/bundle\.([^".]+)\.js/g, './bundle.js?$1');
					content = content.replace(
						/\/_app\/immutable\/assets\/bundle\.([^".]+)\.css/g,
						'./bundle.css?$1'
					);
					content = content.replace(/__sveltekit_[a-z0-9]+/g, '__sveltekit__');

					writeFileSync(indexPath, content, 'utf-8');
					console.log('✓ Updated index.html');

					// Copy bundle.*.js -> bundle.js at output root
					const immutableDir = resolve(outDir, '_app/immutable');
					const bundleDir = resolve(outDir, '_app/immutable/assets');

					if (existsSync(immutableDir)) {
						const jsFiles = readdirSync(immutableDir).filter((f) => f.match(/^bundle\..+\.js$/));
						if (jsFiles.length > 0) {
							copyFileSync(resolve(immutableDir, jsFiles[0]), resolve(outDir, 'bundle.js'));
							// Normalize __sveltekit_<hash> to __sveltekit__ in bundle.js
							const bundleJsPath = resolve(outDir, 'bundle.js');
							let bundleJs = readFileSync(bundleJsPath, 'utf-8');
							bundleJs = bundleJs.replace(/__sveltekit_[a-z0-9]+/g, '__sveltekit__');
							writeFileSync(bundleJsPath, bundleJs, 'utf-8');
							console.log(`✓ Copied ${jsFiles[0]} -> bundle.js`);
						}
					}

					// Copy bundle.*.css -> bundle.css at output root
					if (existsSync(bundleDir)) {
						const cssFiles = readdirSync(bundleDir).filter((f) => f.match(/^bundle\..+\.css$/));
						if (cssFiles.length > 0) {
							copyFileSync(resolve(bundleDir, cssFiles[0]), resolve(outDir, 'bundle.css'));
							console.log(`✓ Copied ${cssFiles[0]} -> bundle.css`);
						}
					}

					// Copy workbox-*.js -> workbox.js at output root
					const workboxFiles = readdirSync(outDir).filter((f) => f.match(/^workbox-[^.]+\.js$/));
					if (workboxFiles.length > 0) {
						copyFileSync(resolve(outDir, workboxFiles[0]), resolve(outDir, 'workbox.js'));
						rmSync(resolve(outDir, workboxFiles[0]), { force: true });
						console.log(`✓ Copied ${workboxFiles[0]} -> workbox.js`);
					}

					// Write version.json with build identifier (overwrites PWA's default)
					writeFileSync(resolve(outDir, 'version.json'), JSON.stringify({ version: buildVersion }));
					console.log('✓ Generated version.json:', buildVersion);

					// Fix sw.js: rewrite _app paths, favicon.svg → favicon.ico, workbox-*.js → workbox.js
					// Inject build version into sw.js so it differs between builds, triggering
					// the browser to detect a new service worker and fire needRefresh.
					const swPath = resolve(outDir, 'sw.js');
					if (existsSync(swPath)) {
						let swContent = readFileSync(swPath, 'utf-8');
						swContent = swContent.replace(/\/_app\/immutable\/bundle\.[^"]+\.js/g, './bundle.js');
						swContent = swContent.replace(
							/\/_app\/immutable\/assets\/bundle\.[^"]+\.css/g,
							'./bundle.css'
						);
						swContent = swContent.replace(/"favicon\.svg"/g, '"favicon.ico"');
						// Rewrite _app/version.json -> version.json
						swContent = swContent.replace(/"_app\/version\.json"/g, '"version.json"');
						// Rewrite workbox-<hash> (import) → workbox
						swContent = swContent.replace(/"\.\/workbox-[a-z0-9]+"/g, '"./workbox"');
						// Rewrite precache paths with leading slash
						swContent = swContent.replace(
							/"\/?_app\/immutable\/bundle\.[^"]+\.js"/g,
							'"./bundle.js"'
						);
						swContent = swContent.replace(
							/"\/?_app\/immutable\/assets\/bundle\.[^"]+\.css"/g,
							'"./bundle.css"'
						);
						// Inject build version as a comment so SW content changes between builds
						swContent = '// Build: ' + buildVersion + '\n' + swContent;
						writeFileSync(swPath, swContent, 'utf-8');
						console.log('✓ Fixed sw.js precache paths + injected build version');
					}

					// Cleanup: remove _app directory (static assets kept for server)
					const appDir = resolve(outDir, '_app');
					if (existsSync(appDir)) {
						rmSync(appDir, { recursive: true, force: true });
						console.log('✓ Removed _app directory');
					}
				} catch (error) {
					console.error('Failed to process build output:', error);
				}
			}, 100);
		}
	};
}
