import {
	readFileSync,
	writeFileSync,
	existsSync,
	readdirSync,
	copyFileSync,
	rmSync
} from 'node:fs';
import { execSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Plugin } from 'vite';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GUIDE_FOR_FRONTEND = `
<!--
  This is a static build of the frontend.
  It is automatically generated by the build process.
  Do not edit this file directly.
  To make changes, refer to the "Web UI" section in the README.
-->
`.trim();

const OUTPUT_DIR = process.env.LLAMA_UI_OUT_DIR ?? './dist';
let processed = false;

/**
 * Apple device dimensions (logical points) and DPR, from Apple HIG.
 * Used to look up correct media query values from generated splash file dimensions.
 */
const APPLE_DEVICES: Record<string, { width: number; height: number; dpr: number }> = {
	// iPhones (DPR 3)
	'1170x2532': { width: 390, height: 844, dpr: 3 }, // iPhone 13, 15
	'1179x2556': { width: 393, height: 852, dpr: 3 }, // iPhone 14, 15 Pro, 16
	'1206x2622': { width: 402, height: 874, dpr: 3 }, // iPhone 16 Plus, 16e
	'1284x2778': { width: 428, height: 926, dpr: 3 }, // iPhone 15 Plus
	'1290x2796': { width: 430, height: 932, dpr: 3 }, // iPhone 15 Pro Max, 16 Pro
	'1320x2868': { width: 440, height: 956, dpr: 3 }, // iPhone 16 Pro Max
	'750x1334': { width: 375, height: 667, dpr: 2 }, // iPhone 6/7/8, 14
	'640x1136': { width: 320, height: 568, dpr: 2 }, // iPhone 6/7/8 Plus
	// iPads (DPR 2)
	'1668x2388': { width: 834, height: 1194, dpr: 2 }, // iPad Air 11", iPad 11"
	'2048x2732': { width: 1024, height: 1366, dpr: 2 }, // iPad Pro 12.9"
	'1640x2360': { width: 820, height: 1180, dpr: 2 }, // iPad Air 10.9"
	'1032x1376': { width: 1032, height: 1376, dpr: 2 }, // iPad Air 13"
	'744x1133': { width: 376, height: 573, dpr: 2 } // iPad mini 8.3"
};

/**
 * Generate iOS splash screen <link> tags from generated apple-splash-*.png files.
 * Returns an array of HTML link strings to be injected into the page head.
 */
function generateSplashScreenLinks(outDir: string): string[] {
	const files = readdirSync(outDir).filter((f) =>
		f.match(/^apple-splash-(portrait|landscape)-(dark-)?\d+x\d+\.png$/)
	);
	if (files.length === 0) return [];

	// Build lookup: "widthxheight" -> { deviceW, deviceH, dpr, orientation }
	const dimMap = new Map<string, { deviceW: number; deviceH: number; dpr: number }>();
	for (const [dims, spec] of Object.entries(APPLE_DEVICES)) {
		const [w, h] = dims.split('x').map(Number);
		// Portrait file dimensions
		dimMap.set(`${w}x${h}`, { deviceW: spec.width, deviceH: spec.height, dpr: spec.dpr });
		// Landscape file dimensions (swapped)
		dimMap.set(`${h}x${w}`, { deviceW: spec.width, deviceH: spec.height, dpr: spec.dpr });
	}

	const lightLinks: string[] = [];
	const darkLinks: string[] = [];

	for (const file of files) {
		const match = file.match(/^apple-splash-(portrait|landscape)-(dark-)?(\d+)x(\d+)\.png$/);
		if (!match) continue;
		const orientation = match[1] as 'portrait' | 'landscape';
		const isDark = !!match[2];
		const pixelW = parseInt(match[3]);
		const pixelH = parseInt(match[4]);

		// Look up device specs from the pixel dimensions
		const key = `${pixelW}x${pixelH}`;
		const spec = dimMap.get(key);
		if (!spec) {
			console.warn(`⚠ Unknown splash screen dimensions: ${key} (${file})`);
			continue;
		}

		const { deviceW, deviceH, dpr } = spec;

		const media = `screen and (device-width: ${deviceW}px) and (device-height: ${deviceH}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: ${orientation})`;
		const href = `/${file}`;

		if (isDark) {
			darkLinks.push(
				`\t\t<link rel="apple-touch-startup-image" media="${media} and (prefers-color-scheme: dark)" href="${href}">`
			);
		} else {
			lightLinks.push(`\t\t<link rel="apple-touch-startup-image" media="${media}" href="${href}">`);
		}
	}

	return [...lightLinks, ...darkLinks];
}

export function llamaCppBuildPlugin(): Plugin {
	return {
		name: 'llamacpp:build',
		apply: 'build',
		closeBundle() {
			setTimeout(() => {
				try {
					if (processed) return;
					processed = true;

					// Build version: explicit env var (from CMake) > git hash > fallback
					let buildVersion = process.env.LLAMA_UI_VERSION;
					if (!buildVersion || buildVersion.trim() === '') {
						try {
							const gitHash = execSync('git rev-parse --short HEAD', {
								cwd: resolve(__dirname, '../..'),
								encoding: 'utf-8'
							}).trim();
							const epoch = Math.floor(Date.now() / 1000);
							buildVersion = `${gitHash}-${epoch}`;
						} catch {
							buildVersion = `fallback-${Date.now()}`;
						}
					}

					const outDir = resolve(OUTPUT_DIR);
					const indexPath = resolve(outDir, 'index.html');
					if (!existsSync(indexPath)) return;

					let content = readFileSync(indexPath, 'utf-8');

					// Generate iOS splash screen link tags from static files
					const splashLinks = generateSplashScreenLinks(outDir);
					if (splashLinks.length > 0) {
						console.log(`✓ Generated ${splashLinks.length} apple-splash link tags`);
						const splashHtml = splashLinks.map((l) => '\t\t' + l).join('\n');
						content = content.replace(/\t*<\/head>/, splashHtml + '\n\t\t</head>');
					}

					content = content.replace(/\r/g, '');
					content = GUIDE_FOR_FRONTEND + '\n' + content;

					// Keep the Vite hash as a query string so each build busts the browser cache
					content = content.replace(/\/_app\/immutable\/bundle\.([^".]+)\.js/g, './bundle.js?$1');
					content = content.replace(
						/\/_app\/immutable\/assets\/bundle\.([^".]+)\.css/g,
						'./bundle.css?$1'
					);
					content = content.replace(/__sveltekit_[a-z0-9]+/g, '__sveltekit__');

					writeFileSync(indexPath, content, 'utf-8');
					console.log('✓ Updated index.html');

					// Copy bundle.*.js -> bundle.js at output root
					const immutableDir = resolve(outDir, '_app/immutable');
					const bundleDir = resolve(outDir, '_app/immutable/assets');

					if (existsSync(immutableDir)) {
						const jsFiles = readdirSync(immutableDir).filter((f) => f.match(/^bundle\..+\.js$/));
						if (jsFiles.length > 0) {
							copyFileSync(resolve(immutableDir, jsFiles[0]), resolve(outDir, 'bundle.js'));
							// Normalize __sveltekit_<hash> to __sveltekit__ in bundle.js
							const bundleJsPath = resolve(outDir, 'bundle.js');
							let bundleJs = readFileSync(bundleJsPath, 'utf-8');
							bundleJs = bundleJs.replace(/__sveltekit_[a-z0-9]+/g, '__sveltekit__');
							writeFileSync(bundleJsPath, bundleJs, 'utf-8');
							console.log(`✓ Copied ${jsFiles[0]} -> bundle.js`);
						}
					}

					// Copy bundle.*.css -> bundle.css at output root
					if (existsSync(bundleDir)) {
						const cssFiles = readdirSync(bundleDir).filter((f) => f.match(/^bundle\..+\.css$/));
						if (cssFiles.length > 0) {
							copyFileSync(resolve(bundleDir, cssFiles[0]), resolve(outDir, 'bundle.css'));
							console.log(`✓ Copied ${cssFiles[0]} -> bundle.css`);
						}
					}

					// Copy workbox-*.js -> workbox.js at output root
					const workboxFiles = readdirSync(outDir).filter((f) => f.match(/^workbox-[^.]+\.js$/));
					if (workboxFiles.length > 0) {
						copyFileSync(resolve(outDir, workboxFiles[0]), resolve(outDir, 'workbox.js'));
						rmSync(resolve(outDir, workboxFiles[0]), { force: true });
						console.log(`✓ Copied ${workboxFiles[0]} -> workbox.js`);
					}

					// Write version.json with build identifier (overwrites PWA's default)
					writeFileSync(resolve(outDir, 'version.json'), JSON.stringify({ version: buildVersion }));
					console.log('✓ Generated version.json:', buildVersion);

					// Fix sw.js: rewrite _app paths, favicon.svg → favicon.ico, workbox-*.js → workbox.js
					// Inject build version into sw.js so it differs between builds, triggering
					// the browser to detect a new service worker and fire needRefresh.
					const swPath = resolve(outDir, 'sw.js');
					if (existsSync(swPath)) {
						let swContent = readFileSync(swPath, 'utf-8');
						// Replace hashed bundle paths with static names + version query param
						swContent = swContent.replace(
							/\/_app\/immutable\/bundle\.[^"]+\.js/g,
							`./bundle.js?v=${buildVersion}`
						);
						swContent = swContent.replace(
							/\/_app\/immutable\/assets\/bundle\.[^"]+\.css/g,
							`./bundle.css?v=${buildVersion}`
						);
						swContent = swContent.replace(/"favicon\.svg"/g, '"favicon.ico"');
						// Rewrite _app/version.json -> version.json
						swContent = swContent.replace(/"_app\/version\.json"/g, '"version.json"');
						// Rewrite workbox-<hash> (import) → workbox
						swContent = swContent.replace(/"\.\/workbox-[a-z0-9]+"/g, '"./workbox"');
						// Rewrite precache paths with leading slash to static names + version
						swContent = swContent.replace(
							/"\/?_app\/immutable\/bundle\.[^"]+\.js"/g,
							`"./bundle.js?v=${buildVersion}"`
						);
						swContent = swContent.replace(
							/"\/?_app\/immutable\/assets\/bundle\.[^"]+\.css"/g,
							`"./bundle.css?v=${buildVersion}"`
						);
						// Inject build version as a comment so SW content changes between builds
						swContent = '// Build: ' + buildVersion + '\n' + swContent;
						writeFileSync(swPath, swContent, 'utf-8');
						console.log('✓ Fixed sw.js precache paths + injected build version');
					}

					// Cleanup: remove _app directory (static assets kept for server)
					const appDir = resolve(outDir, '_app');
					if (existsSync(appDir)) {
						rmSync(appDir, { recursive: true, force: true });
						console.log('✓ Removed _app directory');
					}
				} catch (error) {
					console.error('Failed to process build output:', error);
				}
			}, 100);
		}
	};
}
