//
// test_champq.cpp
//
// Parity + convergence tests for the C++ CHAMP-Q L-BFGS permutation port
// (tessera-champq.cpp), against Python's champq_permute.lbfgs_permutation
// (driving _champq_lbfgs.LBFGS). The fixture is generated by
// fixtures/gen_champq_fixture.py, which runs the Python driver on a seeded
// 24x32 weight + activation scales and records:
//
//   - the per-iteration loss trajectory at the Sinkhorn-projected point
//   - the final permutation and final smoothness proxy
//   - the identity (baseline) smoothness
//
// The C++ port runs the same driver (L-BFGS step, Sinkhorn project,
// recompute) on the same inputs. Gates:
//
//   1. Trajectory parity: each projected loss matches Python within
//      rtol=5e-3 / atol=1e-3. The C++ closure is float32 end-to-end while
//      the Python closure is float64 over f32 inputs, so the early
//      iterations (loss ~ 1e4, where the W @ M matmul accumulates K=32
//      terms) drift by a few parts in 1e3; the tolerance absorbs that
//      while still catching a wrong objective or a missing Sinkhorn step.
//   2. Convergence: the loss decreases (final < initial), and the
//      monotonically-ish property holds (no single iteration more than
//      doubles; the projected point is on the same manifold as the start).
//   3. Final smoothness parity: the recovered permutation's smoothness is
//      within atol=1e-2 relative of Python's. The permutation itself is
//      NOT bit-identical - the relaxed M has many near-ties at K=32 and
//      Hungarian tie-breaking differs across float32/float64 - so we gate
//      on quality (smoothness) instead.
//   4. Valid permutation: each index in [0, in_dim) appears exactly once.
//   5. Identity init smoothness parity: ts_champq_smoothness matches
//      Python's smoothness_proxy on the identity perm.
//
// Fixture: tools/quantize/tessera/fixtures/champq_fixture.json
// Regenerate via: python3 tools/quantize/tessera/fixtures/gen_champq_fixture.py
//

#include "tessera-champq.h"
#include "tessera-lbfgs.h"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdint>
#include <fstream>
#include <string>
#include <vector>

using json = nlohmann::json;

static int g_failures = 0;

#define CHECK(cond, msg)                                                     \
    do {                                                                     \
        if (!(cond)) {                                                       \
            std::printf("FAIL: %s (%s:%d)\n", msg, __FILE__, __LINE__);      \
            g_failures++;                                                    \
        }                                                                    \
    } while (0)

// Resolve a path relative to this source file (so the test works regardless
// of the CWD the harness invokes it from).
static std::string src_relative(const std::string & tail) {
    std::string f = __FILE__;
    size_t slash = f.find_last_of("/\\");
    std::string dir = (slash == std::string::npos) ? "." : f.substr(0, slash);
    return dir + "/" + tail;
}

static std::vector<float> to_floats(const json & j) {
    std::vector<float> out;
    out.reserve(j.size());
    for (const auto & v : j) {
        out.push_back((float)v.get<double>());
    }
    return out;
}

static std::vector<int32_t> to_ints(const json & j) {
    std::vector<int32_t> out;
    out.reserve(j.size());
    for (const auto & v : j) {
        out.push_back((int32_t)v.get<double>());
    }
    return out;
}

struct fixture {
    int64_t out_dim, in_dim, n_iters, sinkhorn_iters, history;
    float binariness;
    std::vector<float> weight, act_scales;
    std::vector<int32_t> l2rank_init_perm;
    std::vector<float> loss_trajectory;
    std::vector<int32_t> final_perm;
    double final_smoothness;
    double identity_smoothness;
    double traj_rtol, traj_atol, smooth_atol;
};

static bool load_fixture(const std::string & path, fixture & fx) {
    std::ifstream in(path);
    if (!in.good()) {
        std::printf("could not open fixture: %s\n", path.c_str());
        return false;
    }
    json j;
    in >> j;

    const auto & P = j["params"];
    fx.out_dim        = P["out_dim"];
    fx.in_dim         = P["in_dim"];
    fx.n_iters        = P["n_iters"];
    fx.sinkhorn_iters = P["sinkhorn_iters"];
    fx.history        = P["history"];
    fx.binariness     = P["binariness"];

    const auto & I = j["inputs"];
    fx.weight     = to_floats(I["weight"]);
    fx.act_scales = to_floats(I["act_scales"]);

    const auto & E = j["expected"];
    fx.l2rank_init_perm = to_ints(E["l2rank_init_perm"]);
    fx.loss_trajectory  = to_floats(E["loss_trajectory"]);
    fx.final_perm       = to_ints(E["final_perm"]);
    fx.final_smoothness   = E["final_smoothness"];
    fx.identity_smoothness = E["identity_smoothness"];

    const auto & T = j["tolerance"];
    fx.traj_rtol   = T["trajectory_rtol"];
    fx.traj_atol   = T["trajectory_atol"];
    fx.smooth_atol = T["smoothness_atol"];
    return true;
}

// combined rel/abs error: |a-b| <= atol + rtol * |b|.
static bool within(double a, double b, double rtol, double atol) {
    double diff = std::fabs(a - b);
    return diff <= atol + rtol * std::fabs(b);
}

int main() {
    const std::string path = src_relative("fixtures/champq_fixture.json");
    fixture fx;
    if (!load_fixture(path, fx)) {
        std::printf("FAIL: could not load fixture %s\n", path.c_str());
        return 1;
    }
    std::printf("loaded fixture: %s\n", path.c_str());
    std::printf("  weight %lldx%lld, iters=%lld sinkhorn=%lld history=%lld "
                "binariness=%.4e\n",
                (long long)fx.out_dim, (long long)fx.in_dim,
                (long long)fx.n_iters, (long long)fx.sinkhorn_iters,
                (long long)fx.history, fx.binariness);

    // Run the C++ port with the same params the fixture used.
    ts_champq_params params = {};
    params.max_iters      = fx.n_iters;
    params.sinkhorn_iters = fx.sinkhorn_iters;
    params.use_lbfgs      = true;
    params.seed           = 0;
    params.act_scales     = fx.act_scales.data();
    params.binariness     = fx.binariness;
    params.history        = fx.history;
    params.projection     = 0;  // hungarian
    params.init           = 0;  // l2rank

    ts_champq_result result;
    CHECK(ts_champq_compute(fx.weight.data(), fx.out_dim, fx.in_dim,
                            &params, &result) == 0,
          "ts_champq_compute returns 0");

    // --- Test 1: trajectory parity ---
    {
        const auto & py = fx.loss_trajectory;
        const auto & cpp = result.loss_history;
        CHECK(cpp.size() == py.size(), "trajectory length matches");
        std::printf("[traj] cpp=%zu py=%zu points\n", cpp.size(), py.size());
        if (cpp.size() == py.size()) {
            int n_bad = 0;
            double max_rel = 0.0;
            double max_abs = 0.0;
            // Report the first/last few explicitly so the test log shows the
            // achieved gap at the worst points (early iterations are largest).
            for (size_t i = 0; i < cpp.size(); i++) {
                double a = cpp[i];
                double b = py[i];
                if (!within(a, b, fx.traj_rtol, fx.traj_atol)) {
                    n_bad++;
                }
                double denom = std::max(std::fabs(a), std::fabs(b));
                double rel = denom > 0.0 ? std::fabs(a - b) / denom : 0.0;
                if (rel > max_rel) max_rel = rel;
                if (std::fabs(a - b) > max_abs) max_abs = std::fabs(a - b);
            }
            std::printf("[traj] loss[0]  cpp=%.6e py=%.6e\n", cpp[0], py[0]);
            std::printf("[traj] loss[1]  cpp=%.6e py=%.6e\n", cpp[1], py[1]);
            std::printf("[traj] loss[-1] cpp=%.6e py=%.6e\n",
                        cpp[cpp.size() - 1], py[py.size() - 1]);
            std::printf("[traj] max_rel=%.3e max_abs=%.3e  "
                        "(gate rtol=%.0e atol=%.0e), %d/%zu outside\n",
                        max_rel, max_abs, fx.traj_rtol, fx.traj_atol,
                        n_bad, cpp.size());
            CHECK(n_bad == 0, "trajectory within rtol/atol of Python");
        }
    }

    // --- Test 2: convergence (loss decreases, monotonically-ish) ---
    {
        const auto & cpp = result.loss_history;
        CHECK(cpp.size() >= 2, "trajectory has at least 2 points");
        if (cpp.size() >= 2) {
            double first = cpp.front();
            double last  = cpp.back();
            std::printf("[conv] first=%.6e last=%.6e ratio=%.4e\n",
                        first, last, last / first);
            CHECK(last < first, "loss decreases over the run");

            // Monotonically-ish: no single projected step more than 1.5x the
            // running minimum. The objective is non-convex but the
            // Armijo-gated step + Sinkhorn projection keeps the trajectory
            // well-behaved; a >1.5x spike signals a gradient/project bug.
            int spikes = 0;
            double run_min = cpp[0];
            for (size_t i = 1; i < cpp.size(); i++) {
                if (cpp[i] < run_min) run_min = cpp[i];
                if (cpp[i] > 1.5 * run_min) spikes++;
            }
            std::printf("[conv] %d spikes above 1.5x running min\n", spikes);
            CHECK(spikes == 0, "no large upward spikes in loss trajectory");
        }
    }

    // --- Test 3: valid permutation ---
    {
        CHECK((int64_t)result.perm.size() == fx.in_dim, "perm length == in_dim");
        if ((int64_t)result.perm.size() == fx.in_dim) {
            std::vector<int> seen(fx.in_dim, 0);
            for (int64_t i = 0; i < fx.in_dim; i++) {
                int32_t v = result.perm[i];
                if (v < 0 || v >= fx.in_dim) {
                    std::printf("FAIL: perm[%lld]=%d out of range\n",
                                (long long)i, v);
                    g_failures++;
                    break;
                }
                seen[v]++;
            }
            bool ok = true;
            for (int64_t i = 0; i < fx.in_dim; i++) {
                if (seen[i] != 1) ok = false;
            }
            CHECK(ok, "perm is a valid permutation of [0, in_dim)");
        }
    }

    // --- Test 4: final smoothness quality parity ---
    //
    // The recovered permutation may differ from Python's (the relaxed M has
    // near-ties and Hungarian tie-breaking is sensitive to f32-vs-f64
    // rounding), so we gate on the quality metric (smoothness proxy) rather
    // than bit-identical indices. Quality parity: the C++ smoothness is
    // within smooth_atol relative of Python's, and both beat the identity
    // baseline by a similar margin.
    {
        double cpp_smooth = (double)result.smoothness;
        double py_smooth  = fx.final_smoothness;
        double id_smooth  = fx.identity_smoothness;
        double rel = std::fabs(cpp_smooth - py_smooth) /
                     std::max(std::fabs(py_smooth), 1e-30);
        std::printf("[quality] cpp_smooth=%.4e py_smooth=%.4e rel=%.3e "
                    "(gate %.0e)\n",
                    cpp_smooth, py_smooth, rel, fx.smooth_atol);
        std::printf("[quality] identity=%.4e  cpp_improvement=%.4f%%  "
                    "py_improvement=%.4f%%\n",
                    id_smooth,
                    100.0 * (id_smooth - cpp_smooth) / id_smooth,
                    100.0 * (id_smooth - py_smooth) / id_smooth);
        CHECK(rel <= fx.smooth_atol,
              "final smoothness within smooth_atol of Python");
        // Both should improve on the identity baseline.
        CHECK(cpp_smooth <= id_smooth * 1.001,
              "C++ perm at least as good as identity baseline");
    }

    // --- Test 5: smoothness_proxy parity on identity ---
    //
    // ts_champq_smoothness is pure float32 arithmetic on the same inputs the
    // Python smoothness_proxy reduces in float64, so this is a tight gate on
    // the proxy formula (including the act_scales weighting).
    {
        std::vector<int32_t> id_perm(fx.in_dim);
        for (int64_t i = 0; i < fx.in_dim; i++) id_perm[i] = (int32_t)i;
        double cpp_id = ts_champq_smoothness(fx.weight.data(), id_perm.data(),
                                             fx.act_scales.data(),
                                             fx.out_dim, fx.in_dim);
        double py_id = fx.identity_smoothness;
        double rel = std::fabs(cpp_id - py_id) / std::fabs(py_id);
        std::printf("[proxy] identity cpp=%.6e py=%.6e rel=%.3e\n",
                    cpp_id, py_id, rel);
        CHECK(rel <= 5e-5, "smoothness proxy matches Python (identity)");
    }

    // --- Test 6: L2-rank init parity ---
    //
    // The init permutation feeds the rest of the trajectory, so it must
    // match Python's compute_champq_permutation. Ties (equal column norms)
    // are resolved by ascending index in both implementations.
    {
        // Reconstruct the C++ init by running with use_lbfgs=false: the
        // result perm is the L2-rank init's Hungarian projection. For a
        // permutation matrix init, Hungarian returns the embedded perm.
        ts_champq_params p0 = params;
        p0.use_lbfgs = false;
        ts_champq_result r0;
        CHECK(ts_champq_compute(fx.weight.data(), fx.out_dim, fx.in_dim,
                                &p0, &r0) == 0, "init-only run ok");
        bool match = r0.perm.size() == fx.l2rank_init_perm.size();
        for (size_t i = 0; match && i < r0.perm.size(); i++) {
            if (r0.perm[i] != fx.l2rank_init_perm[i]) match = false;
        }
        std::printf("[init] L2-rank perm %s Python\n",
                    match ? "matches" : "DIFFERS from");
        if (!match) {
            std::printf("[init] cpp: ");
            for (auto v : r0.perm) std::printf("%d ", v);
            std::printf("\n[inix] py:  ");
            for (auto v : fx.l2rank_init_perm) std::printf("%d ", v);
            std::printf("\n");
        }
        CHECK(match, "L2-rank init permutation matches Python");
    }

    if (g_failures == 0) {
        printf("PASS\n");
        return 0;
    }
    printf("FAIL (%d failures)\n", g_failures);
    return 1;
}
