#!/usr/bin/env python3
# AOT-compile FLA's fused_recurrent_gated_delta_rule_fwd_kernel for a set of (H, HV, S) configs into
# self-contained C (embedded cubin), one specialization per config. Emits, into ppu_so/gdn/aot/:
#   gdn_rec_<H>_<HV>_<S>.<suffix>.c/.h   (per config)
#   ppu_gdn_dispatch.c                    (C ABI ppu_gdn_recurrent(...) that switch-dispatches by shape)
#
# Torch-free/python-free at runtime: the .c files compile with gcc and link with -lcuda (driver API).
# Runtime maps ggml GDN (non-KDA, K_snapshot==1, contiguous, F32) 1:1 to FLA (math+layout verified identical).
#
# Usage:  FLA_ROOT=/path/to/flash-linear-attention python3 aot_recurrent.py "H,HV,S" ["H,HV,S" ...]
import os, sys, subprocess, re

HERE = os.path.dirname(os.path.abspath(__file__))
FLA  = os.environ.get("FLA_ROOT", "")
if not FLA or not os.path.isdir(FLA):
    sys.exit("set FLA_ROOT to the flash-linear-attention checkout")
OUT = os.path.join(HERE, "aot")
os.makedirs(OUT, exist_ok=True)

KN = "fused_recurrent_gated_delta_rule_fwd_kernel"
# shim exposes the unwrapped JITFunction under its real name (kernel-name must equal the cubin symbol == __name__)
SHIM = os.path.join(OUT, "_rec_shim.py")
with open(SHIM, "w") as f:
    f.write(f"import sys; sys.path.insert(0, {FLA!r})\n"
            f"import triton\n"
            f"from fla.ops.gated_delta_rule.fused_recurrent import {KN} as _k\n"
            f"_u=_k\n"
            f"while not isinstance(_u, triton.runtime.JITFunction) and hasattr(_u,'fn'): _u=_u.fn\n"
            f"{KN}=_u\n")

def next_pow2(x):
    p = 1
    while p < x: p <<= 1
    return p

def aot_one(H, HV, S):
    K = V = S
    BK = next_pow2(K)
    BV = min(8, next_pow2(V))
    NV = (V + BV - 1) // BV
    # signature order = kernel args; constexprs pinned. Our ggml mapping: USE_G=1, IS_BETA_HEADWISE=1,
    # USE_INITIAL_STATE=1, STORE_FINAL_STATE=1, all else 0. Unused ptrs (gk,gv,A_log,dt_bias,cu_seqlens) -> NULL.
    consts = f"{H},{HV},{K},{V},{BK},{BV},1,0,0,0,1,1,1,1,0,0,0,0,0"
    sig = ("*fp32:16,*fp32:16,*fp32:16,*fp32:16,*fp32,*fp32,*fp32:16,*fp32,*fp32,"
           "*fp32:16,*fp32:16,*fp32:16,*i32,fp32,i32," + consts)
    name = f"gdn_rec_{H}_{HV}_{S}"
    cmd = [sys.executable, "-m", "triton.tools.compile", "--kernel-name", KN,
           "--out-name", name, "-o", os.path.join(OUT, name),
           "--num-warps", "1", "--num-stages", "3",
           "--grid", f"{NV},{HV},1", "--signature", sig, SHIM]
    env = dict(os.environ, PYTHONPATH=FLA)
    subprocess.run(cmd, check=True, env=env)
    # find generated files, fix the fp32-scalar ABI bug (double scale -> float scale)
    cf = [f for f in os.listdir(OUT) if f.startswith(name + ".") and f.endswith(".c")][0]
    hf = cf[:-2] + ".h"
    for fn in (cf, hf):
        p = os.path.join(OUT, fn)
        s = open(p).read().replace("double scale", "float scale")
        open(p, "w").write(s)
    suffix = cf[len(name) + 1:-2]
    print(f"  AOT {name}  BK={BK} BV={BV} NV={NV}  suffix={suffix}")
    return dict(H=H, HV=HV, S=S, NV=NV, BV=BV, name=name, suffix=suffix, cfile=cf, hfile=hf)

def main():
    cfgs = sys.argv[1:] or ["32,32,128", "16,16,64", "4,4,64", "4,8,64", "32,32,64"]
    specs = []
    for c in cfgs:
        H, HV, S = (int(x) for x in c.split(","))
        specs.append(aot_one(H, HV, S))
    emit_dispatch(specs)

def emit_dispatch(specs):
    # ppu_gdn_dispatch.c : the C ABI. Loops sequences in C (grid is per-sequence const), advancing pointers,
    # calling the matching AOT entry. Returns -1 if no specialization matches the (H,HV,S) shape.
    inc = "\n".join(f'#include "{s["name"]}.{s["suffix"]}.h"' for s in specs)
    loads = "\n".join(f'    load_{s["name"]}_{s["suffix"]}();' for s in specs)
    arms = []
    for s in specs:
        entry = f'{s["name"]}_{s["suffix"]}'
        arms.append(f"""    if (H=={s['H']} && HV=={s['HV']} && S=={s['S']}) {{
        for (int n = 0; n < n_seqs; ++n) {{
            const float * qn = q + (size_t)n*T*H*S;
            const float * kn = k + (size_t)n*T*H*S;
            const float * vn = v + (size_t)n*T*HV*S;
            const float * gn = g + (size_t)n*T*HV;
            const float * bn = beta + (size_t)n*T*HV;
            const float * h0n = h0 + (size_t)n*HV*S*S;
            float * on = o + (size_t)n*T*HV*S;
            float * htn = ht + (size_t)n*HV*S*S;
            CUresult r = {entry}((CUstream)stream,
                (CUdeviceptr)qn,(CUdeviceptr)kn,(CUdeviceptr)vn,(CUdeviceptr)gn,
                (CUdeviceptr)0,(CUdeviceptr)0,(CUdeviceptr)bn,(CUdeviceptr)0,(CUdeviceptr)0,
                (CUdeviceptr)on,(CUdeviceptr)h0n,(CUdeviceptr)htn,(CUdeviceptr)0,scale,T);
            if (r != CUDA_SUCCESS) return -2;
        }}
        return 0;
    }}""")
    body = f"""// AUTO-GENERATED by aot_recurrent.py -- do not edit.
// C ABI over FLA's AOT'd recurrent gated-delta-rule kernel. Torch-free/python-free; links -lcuda.
#include <cuda.h>
#include <stddef.h>
#include <pthread.h>
{inc}

static pthread_once_t g_once = PTHREAD_ONCE_INIT;
static void load_all(void) {{
{loads}
}}

// ggml GDN (non-KDA, K_snapshot==1, contiguous, F32): q,k[n,T,H,S] v[n,T,HV,S] g,beta[n,T,HV]
// h0,ht[n,HV,S,S] o[n,T,HV,S]. Returns 0 on success, -1 unsupported shape (-> inline fallback), -2 launch error.
int ppu_gdn_recurrent(const float * q, const float * k, const float * v, const float * g,
                      const float * beta, const float * h0, float * o, float * ht,
                      int n_seqs, int T, int H, int HV, int S, float scale, void * stream) {{
    pthread_once(&g_once, load_all);
{chr(10).join(arms)}
    return -1; // no specialization for this (H,HV,S)
}}
"""
    p = os.path.join(OUT, "ppu_gdn_dispatch.c")
    open(p, "w").write(body)
    print(f"  dispatch -> {p}  ({len(specs)} specializations)")

if __name__ == "__main__":
    main()
