/**
 * versionStore - Build version information
 *
 * Reads the build version from the `version.json` artifact generated by the
 * Vite production build. In dev mode (via `npm run dev`), falls back to
 * `import.meta.env.DEV`'s truthy value as a placeholder since the artifact
 * is not produced.
 */

import { browser } from '$app/environment';

let version = $state<string>('');

async function loadVersion() {
	if (!browser) return;

	// In dev mode the version.json artifact doesn't exist - use a simple fallback
	if (import.meta.env.DEV) {
		version = 'dev';
		return;
	}

	try {
		const res = await fetch('/version.json');
		if (res.ok) {
			const data = await res.json();
			version = data.version ?? '';
		}
	} catch {
		// version.json missing or unreachable - leave as empty string
	}
}

loadVersion();

export const versionStore = {
	get value(): string {
		return version;
	}
};
