/**
 * versionStore - Build version information
 *
 * Reads the build version from the `version.json` artifact generated by the
 * Vite production build. In dev mode (via `npm run dev`), falls back to
 * `import.meta.env.DEV`'s truthy value as a placeholder since the artifact
 * is not produced.
 *
 * The version string is used for version mismatch detection (non-PWA users).
 * The SW caches the `?cache=true` variant so the PWA is installable, while
 * the uncached URL always stays fresh for server-upgrade detection.
 */

import { browser } from '$app/environment';
import { base } from '$app/paths';
import { SvelteURLSearchParams } from 'svelte/reactivity';

let version = $state<string>('');

async function loadVersion() {
	if (!browser) return;

	// In dev mode the version.json artifact doesn't exist - use a simple fallback
	if (import.meta.env.DEV) {
		version = 'dev';
		return;
	}

	try {
		const res = await fetch(`${base}/version.json`, { cache: 'no-store' });
		if (res.ok) {
			const data = await res.json();
			version = data.version ?? '';
		}
	} catch {
		// version.json missing or unreachable - leave as empty string
	}
}

loadVersion();

/** Returns true when the app is running as an installed PWA (via ?pwa=1 in the URL).
 *  This allows the frontend to distinguish "running as installed app" vs "running in browser". */
export function isPwaMode(): boolean {
	return browser && new SvelteURLSearchParams(window.location.search).has('pwa');
}

export const versionStore = {
	get value(): string {
		return version;
	}
};
