function(ggml_sycl_normalize_arch arch output)
    string(TOLOWER "${arch}" arch)
    string(REPLACE "_" "-" arch "${arch}")
    string(REGEX REPLACE "[, \t]+" ";" targets "${arch}")
    list(FILTER targets EXCLUDE REGEX "^$")
    list(REMOVE_DUPLICATES targets)
    list(JOIN targets "," targets)
    set(${output} "${targets}" PARENT_SCOPE)
endfunction()

# AUTO admits only AOT names with recorded successful gather-kernel links. See docs/backend/SYCL.md.
function(ggml_sycl_xmx_gather_targets mode arch output)
    string(TOUPPER "${mode}" mode)
    if (NOT mode MATCHES "^(AUTO|ON|OFF)$")
        message(FATAL_ERROR "GGML_SYCL_XMX_GATHER must be AUTO, ON, or OFF (got '${mode}')")
    endif()
    ggml_sycl_normalize_arch("${arch}" arch)
    string(REPLACE "," ";" targets "${arch}")
    set(selected "")
    if (NOT mode STREQUAL "OFF")
        foreach(target IN LISTS targets)
            if (mode STREQUAL "ON" OR target MATCHES "^(bmg-g21|xe2-hpg|pvc|lnl-m)$")
                list(APPEND selected "${target}")
            endif()
        endforeach()
    endif()
    list(REMOVE_DUPLICATES selected)
    if (mode STREQUAL "OFF" OR (NOT "${targets}" STREQUAL "" AND "${selected}" STREQUAL ""))
        set(selected "OFF")
    elseif("${targets}" STREQUAL "")
        set(selected "JIT")
    else()
        list(JOIN selected "," selected)
    endif()
    set(${output} "${selected}" PARENT_SCOPE)
endfunction()
