from __future__ import annotations

import re
from collections.abc import Iterable
from typing import TYPE_CHECKING

import torch

if TYPE_CHECKING:
    from torch import Tensor

from .base import ModelBase, TextModel, gguf, logger


@ModelBase.register("LagunaForCausalLM")
class LagunaModel(TextModel):
    model_arch = gguf.MODEL_ARCH.LAGUNA
    _experts: list[dict] | None = None
    _gate_types: list[str] | None = None

    # --- vocab ---------------------------------------------------------------

    def set_vocab(self) -> None:
        # Laguna ships a GPT-2 byte-level BPE tokenizer. The BPE pre-tokenizer
        # variant ("laguna") is registered via get_vocab_base_pre()'s hash
        # dispatcher; that table is regenerated by convert_hf_to_gguf_update.py
        # before merging upstream.
        self._set_vocab_gpt2()

        # Laguna's eos_token_id is a LIST: token 2 (the EOS marker, which also
        # serves as BOS) and token 24 (</assistant>, the chat turn-end).
        # _set_vocab_gpt2 records only the scalar eos (2), so the GGUF never
        # learns that </assistant> ends generation. Register the remaining
        # eos id(s) as the end-of-turn token; llama.cpp folds eot into its EOG
        # set unconditionally, so the model halts on </assistant> natively
        # without client-side stop strings. See config.json eos_token_id=[2, 24].
        eos_ids = self.hparams.get("eos_token_id")
        if isinstance(eos_ids, list):
            bos_id = self.hparams.get("bos_token_id")
            extra = [e for e in eos_ids if e != bos_id]
            if extra:
                self.gguf_writer.add_eot_token_id(extra[0])
                logger.info(
                    f"gguf: registered eot_token_id={extra[0]} from eos list {eos_ids}"
                )

        # Inline the chat template. The HF repo ships chat_template.jinja
        # separately and tokenizer_config.json references it via
        #     "chat_template": "{% include 'chat_template.jinja' %}"
        # llama.cpp's embedded Jinja renderer does not resolve {% include %} at
        # runtime, so write the file's resolved contents into the GGUF directly.
        chat_template_path = self.dir_model / "chat_template.jinja"
        if chat_template_path.is_file():
            tmpl = chat_template_path.read_text(encoding="utf-8")
            self.gguf_writer.add_chat_template(tmpl)
            logger.info(f"gguf: inlined chat_template.jinja ({len(tmpl)} chars)")

    # --- hparams -------------------------------------------------------------

    def set_gguf_parameters(self) -> None:
        super().set_gguf_parameters()
        hparams = self.hparams

        # super() covers the standard keys (block/context/embedding/ffn length,
        # head_count_kv, key/value_length from the explicit head_dim, rms_eps,
        # file_type). It does not emit vocab_size for the gpt2 vocab path, so set
        # it here, and override the scalar head_count with a per-layer ARRAY:
        # XS.2 varies heads per layer (full=48, SWA=64) via
        # num_attention_heads_per_layer; M.1 is uniform and omits it, so build a
        # constant list from the scalar num_attention_heads.
        self.gguf_writer.add_vocab_size(hparams["vocab_size"])

        per_layer_heads = hparams.get("num_attention_heads_per_layer")
        if not per_layer_heads:
            per_layer_heads = [hparams["num_attention_heads"]] * hparams["num_hidden_layers"]
        assert len(per_layer_heads) == hparams["num_hidden_layers"], (
            f"num_attention_heads_per_layer length {len(per_layer_heads)} != "
            f"num_hidden_layers {hparams['num_hidden_layers']}"
        )
        self.gguf_writer.add_head_count(per_layer_heads)

        # Resolve + validate the attention gate type now, so an inconsistent
        # `gating` field fails at conversion time rather than silently. See
        # _attn_gate_types.
        self._attn_gate_types()

        # SWA: scalar window size. M.1 has no sliding window (sliding_window=0),
        # so the key is omitted and the loader leaves swa_type = NONE. For XS.2
        # the full/sliding interleave (full attention every 4th layer, dense
        # first) is applied by the graph builder's sliding-window period.
        sliding_window = hparams.get("sliding_window") or 0
        if sliding_window > 0:
            self.gguf_writer.add_sliding_window(sliding_window)

        # MoE
        self.gguf_writer.add_expert_count(self.find_hparam(["num_experts", "num_local_experts"]))
        self.gguf_writer.add_expert_used_count(hparams["num_experts_per_tok"])
        self.gguf_writer.add_expert_feed_forward_length(hparams["moe_intermediate_size"])
        self.gguf_writer.add_expert_shared_feed_forward_length(hparams["shared_expert_intermediate_size"])
        self.gguf_writer.add_expert_weights_norm(True)  # HF reference always sum-normalises after top-k
        self.gguf_writer.add_expert_weights_scale(float(hparams["moe_routed_scaling_factor"]))
        self.gguf_writer.add_expert_gating_func(gguf.ExpertGatingFuncType.SIGMOID)

        # Dense-vs-MoE structure: a run of leading dense layers (XS.2 has 1,
        # M.1 has 3) followed by MoE layers. `leading_dense_block_count` is what
        # the loader reads to decide which layers are dense.
        mlp_layer_types: list[str] = hparams["mlp_layer_types"]
        leading_dense = 0
        for t in mlp_layer_types:
            if t == "dense":
                leading_dense += 1
            else:
                break
        self.gguf_writer.add_leading_dense_block_count(leading_dense)

        # Per-layer-type RoPE. XS.2 has both full_attention and sliding_attention
        # rope configs; M.1 has only full_attention (no SWA). The _swa mirrors are
        # emitted only when a sliding config exists.
        rope_params = hparams["rope_parameters"]
        full_rope = rope_params["full_attention"]
        swa_rope = rope_params.get("sliding_attention")

        # `partial_rotary_factor` differs per layer type (XS.2 full=0.5 rotates
        # the first 64 of 128 dims, swa=1.0 rotates all 128; M.1 full=1.0).
        full_rot = int(head_dim * float(full_rope.get("partial_rotary_factor", 1.0)))
        self.gguf_writer.add_rope_dimension_count(full_rot)
        self.gguf_writer.add_rope_freq_base(float(full_rope["rope_theta"]))
        if swa_rope is not None:
            swa_rot = int(head_dim * float(swa_rope.get("partial_rotary_factor", 1.0)))
            self.gguf_writer.add_rope_dimension_count_swa(swa_rot)
            self.gguf_writer.add_rope_freq_base_swa(float(swa_rope["rope_theta"]))

        # YaRN scaling on full layers. SWA layers use rope_type="default";
        # the C++ graph builder hardcodes "no YaRN on SWA layers" — we don't
        # emit any *_swa variants of YaRN params. (If a future variant
        # applies YaRN to SWA, we'd add `_swa` mirrors of these keys then.)
        rope_type = full_rope.get("rope_type", "default")
        if rope_type == "yarn":
            self.gguf_writer.add_rope_scaling_type(gguf.RopeScalingType.YARN)
            self.gguf_writer.add_rope_scaling_factor(float(full_rope["factor"]))
            self.gguf_writer.add_rope_scaling_orig_ctx_len(int(full_rope["original_max_position_embeddings"]))
            self.gguf_writer.add_rope_scaling_yarn_attn_factor(float(full_rope.get("attention_factor", 1.0)))
            self.gguf_writer.add_rope_scaling_yarn_beta_fast(float(full_rope.get("beta_fast", 32.0)))
            self.gguf_writer.add_rope_scaling_yarn_beta_slow(float(full_rope.get("beta_slow", 1.0)))
        elif rope_type != "default":
            raise NotImplementedError(
                f"Unsupported rope_type for full_attention: {rope_type!r}. "
                f"Only 'yarn' and 'default' are recognised."
            )

    def _attn_gate_types(self) -> list[str]:
        """Per-layer attention output gate type: "per_head" or "per_element".

        `gating_types` (per layer) is authoritative when present; otherwise the
        scalar `gating` field is used (the "per-element"/"per-head" string, or
        the legacy boolean True == per-head, as in Laguna-XS.2).

        Fails loudly when the model is per-element but the `gating` field does
        not declare that as a string: runtimes that key off `gating` (vLLM,
        transformers) ignore gating_types and read a bare boolean True as
        per-head, silently corrupting the model. Surfacing it here keeps a
        broken checkpoint from being packaged as if it were fine.
        """
        if self._gate_types is not None:
            return self._gate_types
        hparams = self.hparams
        n_layer = hparams["num_hidden_layers"]
        gating = hparams.get("gating")
        gating_types = hparams.get("gating_types")

        def _norm(t: object) -> str:
            sval = str(t).replace("-", "_")
            if sval in ("per_element", "per_head"):
                return sval
            raise ValueError(f"Laguna: unrecognised attention gate type {t!r}")

        if gating_types:
            assert len(gating_types) == n_layer, (
                f"gating_types length {len(gating_types)} != num_hidden_layers {n_layer}")
            types = [_norm(t) for t in gating_types]
        elif isinstance(gating, str):
            types = [_norm(gating)] * n_layer
        elif gating is True:
            types = ["per_head"] * n_layer
        else:
            raise ValueError(
                f"Laguna: cannot determine attention gate type "
                f"(gating={gating!r}, gating_types={gating_types!r})")

        if any(t == "per_element" for t in types) and not (
                isinstance(gating, str) and _norm(gating) == "per_element"):
            raise ValueError(
                f"Laguna config declares a per-element attention gate but "
                f"`gating`={gating!r} is not the string \"per-element\". Runtimes that "
                f"read `gating` (vLLM, transformers) will mis-handle this checkpoint as "
                f"per-head. Set gating=\"per-element\" in the source config.")

        self._gate_types = types
        return types

    # --- tensor handling -----------------------------------------------------

    def modify_tensors(self, data_torch: Tensor, name: str, bid: int | None) -> Iterable[tuple[str, Tensor]]:
        # Per-expert MoE weights: model.layers.{bid}.mlp.experts.{xid}.{w}.weight.
        # Only the NUMBERED per-expert weights are stacked; the router bias
        # (mlp.experts.e_score_correction_bias) takes the normal mapping path.
        if re.search(r"mlp\.experts\.\d+\.", name):
            n_experts = self.find_hparam(["num_local_experts", "num_experts"])
            assert bid is not None
            if self._experts is None:
                self._experts = [{} for _ in range(self.block_count)]
            self._experts[bid][name] = data_torch
            needed = [f"model.layers.{bid}.mlp.experts.{x}.{w}.weight"
                      for x in range(n_experts) for w in ("gate_proj", "up_proj", "down_proj")]
            if all(e in self._experts[bid] for e in needed):
                for w_name in ["gate_proj", "up_proj", "down_proj"]:
                    datas = [self._experts[bid][f"model.layers.{bid}.mlp.experts.{x}.{w_name}.weight"]
                             for x in range(n_experts)]
                    stacked = torch.stack(datas, dim=0)
                    merged = f"model.layers.{bid}.mlp.experts.{w_name}.weight"
                    yield from TextModel.modify_tensors(self, stacked, merged, bid)
                self._experts[bid].clear()
                return
            return
        # Cross-check the gate projection width against the declared gate type;
        # a mismatch means the weights and config disagree -> fail, do not guess.
        if bid is not None and name.endswith("self_attn.g_proj.weight"):
            heads = (self.hparams.get("num_attention_heads_per_layer")
                     or [self.hparams["num_attention_heads"]] * self.hparams["num_hidden_layers"])
            n_head = heads[bid]
            head_dim = self.hparams["head_dim"]
            gate_type = self._attn_gate_types()[bid]
            expected = n_head * head_dim if gate_type == "per_element" else n_head
            out_features = int(data_torch.shape[0])
            if out_features != expected:
                raise ValueError(
                    f"Laguna layer {bid}: g_proj output width {out_features} contradicts the "
                    f"declared {gate_type} gate (expected {expected}); weights and config disagree.")

        yield from TextModel.modify_tensors(self, data_torch, name, bid)
