#!/usr/bin/env bash
# Generate the "lib" branch: a pruned, library-only SDK tree (llamalib).
#
# The lib branch is a generated artifact - never edit it by hand. All
# enablement (LLAMA_DOWNLOAD option, EXISTS guards in CMake) lives on the
# source branch; this script only deletes directories and commits the result.
# Re-run after every upstream sync to refresh the branch.
#
# Usage: scripts/prune-to-lib.sh [--from <ref>] [--branch <name>] [--no-check]
#   --from <ref>    source ref to prune (default: master)
#   --branch <name> target branch to (re)create (default: lib)
#   --no-check      skip the CMake configure sanity check

set -euo pipefail

SRC_REF="master"
LIB_BRANCH="lib"
DO_CHECK=1

while [ $# -gt 0 ]; do
    case "$1" in
        --from)   SRC_REF="$2";    shift 2 ;;
        --branch) LIB_BRANCH="$2"; shift 2 ;;
        --no-check) DO_CHECK=0;    shift ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    echo "ERROR: working tree has uncommitted changes; commit or stash first" >&2
    exit 1
fi

SRC_SHA="$(git rev-parse --verify "${SRC_REF}^{commit}")"

# git branch -f refuses to move a branch that is checked out in any worktree
if git worktree list --porcelain | grep -qx "branch refs/heads/${LIB_BRANCH}"; then
    echo "ERROR: branch '${LIB_BRANCH}' is checked out in a worktree; detach it first" >&2
    echo "  (git -C <worktree> checkout --detach)" >&2
    exit 1
fi

# directories removed from the SDK tree; paths absent in a given tree are skipped
PRUNE_PATHS=(
    tools/batched-bench
    tools/cli
    tools/completion
    tools/cvector-generator
    tools/export-lora
    tools/fit-params
    tools/gguf-split
    tools/imatrix
    tools/mtmd
    tools/parser
    tools/results
    tools/server
    tools/tokenize
    tools/tts
    tools/ui
    app
    examples
    pocs
    ci
    media
    models
    requirements
    skills
    bench-a770
    benches
    sweep-logs
    conversion
    gguf-py
    # conversion entry points are dead without gguf-py
    convert_hf_to_gguf.py
    convert_hf_to_gguf_update.py
    convert_llama_ggml_to_gguf.py
    convert_lora_to_gguf.py
)

WT="$(mktemp -d "${TMPDIR:-/tmp}/llamalib-prune.XXXXXX")"
cleanup() {
    git worktree remove --force "$WT" 2>/dev/null || true
    rm -rf "$WT"
}
trap cleanup EXIT

git worktree add --detach "$WT" "$SRC_SHA" >/dev/null

pushd "$WT" >/dev/null

for p in "${PRUNE_PATHS[@]}"; do
    if [ -e "$p" ]; then
        git rm -r -q -- "$p"
    fi
done

# docs: keep only docs/research (dated evidence corpus) and the SDK guide
if [ -d docs ]; then
    for d in docs/*; do
        # nullglob is not set, so an empty docs/ leaves the literal "docs/*"
        # here and git rm would abort the script under set -e.
        [ -e "$d" ] || continue
        [ "$d" = "docs/research" ] && continue
        [ "$d" = "docs/SDK.md" ] && continue
        git rm -r -q -- "$d"
    done
fi

if [ "$DO_CHECK" = 1 ]; then
    echo "configure sanity check (CPU-only) ..."
    CHECK_DIR="$WT/.prune-check"
    if ! cmake -S "$WT" -B "$CHECK_DIR" \
            -DLLAMA_DOWNLOAD=OFF \
            -DLLAMA_BUILD_TESTS=ON \
            -DLLAMA_BUILD_TOOLS=ON \
            -DLLAMA_BUILD_EXAMPLES=ON \
            -DLLAMA_BUILD_SERVER=OFF \
            > "$CHECK_DIR.log" 2>&1; then
        echo "ERROR: CMake configure failed on the pruned tree; branch NOT updated" >&2
        echo "log: $CHECK_DIR.log (worktree preserved: $WT)" >&2
        trap - EXIT
        exit 1
    fi
    rm -rf "$CHECK_DIR" "$CHECK_DIR.log"
fi

git commit -q -m "lib: prune to SDK tree

Generated by scripts/prune-to-lib.sh from ${SRC_SHA} (${SRC_REF}).
Do not edit this branch by hand; re-run the script after upstream syncs."

NEW_SHA="$(git rev-parse HEAD)"
popd >/dev/null

git branch -f "$LIB_BRANCH" "$NEW_SHA"
echo "branch '$LIB_BRANCH' -> $NEW_SHA (source $SRC_SHA)"
