/**=============================================================================
@file
    qhcg_approximation.h

@brief
    Header file of polynomial approximation generated by QHCG

Copyright (c) 2020 Qualcomm Technologies Incorporated.
All Rights Reserved. Qualcomm Proprietary and Confidential.
=============================================================================**/

#ifndef __qhcg_approximation__
#define __qhcg_approximation__

#include <stdint.h>

int32_t qhcg_approximation(float *inputs, float *outputs, uint32_t length,
    float limit_left, float limit_right
);

#endif /* __qhcg_approximation__ */
