name: apply power8 vec msum

on:
  push:
    branches:
      - power8-vec-msum

permissions:
  contents: write

jobs:
  apply:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Apply patch
        run: |
          git apply --whitespace=nowarn .github/patches/power8-vec-msum.patch
          rm .github/workflows/power8-vec-msum.yml
          rm .github/patches/power8-vec-msum.patch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "ggml: use vec_msum in Q4_K VSX dot product inner loop"
          git push
